### ISSUE TITLE
Information component has wrong code in detail 

### ISSUE THREAD

**Issue by FurkanSezal** [web3ui/web3uikit#1007]
The informatin component has probably old code example. It should be <Information  not <Info 
![image](https://user-images.githubusercontent.com/102124127/213829990-ffc97a5b-de8e-4118-b0d6-d893c4a6b49d.png)

**Comment by BillyG83** [comment]
what the heck? i feel like Storybook is falling apart under the weight of our kit @AbhinavMV LOL

**Comment by AbhinavMV** [comment]
Hahahaha looks like it @BillyG83  😆 

though for this case, I think we just made a small mistake while importing the component, this should be a good first issue

**Comment by SidharthK2** [comment]
Hey! is this issue still open? I'd like to work on it.

**Comment by AbhinavMV** [comment]
Hey @SidharthK2 
I have assigned this issue to you 
If you need any help you can always ping us on moralis discord, web3uikit channel 🥂 
Thankyou
