### ISSUE TITLE
Try the NFT but get Nothing

### ISSUE THREAD

**Issue by Alvin-4550** [web3ui/web3uikit#1056]
dears:
I try to test this  UI in
 https://web3ui.github.io/web3uikit/?path=/docs/1-web3-parse-nft--crypto-punk-01,
<NFT
        address="0xd774557b647330c91bf44cfeab205095f7e6c367"
        chain="eth"
        fetchMetadata
        tokenId="5179"
    />

![image](https://user-images.githubusercontent.com/2723228/229055648-3dcec3ad-0414-4863-98b3-fba0cd8eb468.png)

but get nothing
what i'm missing?

**Comment by BillyG83** [comment]
you are not missing much @Alvin-4550 those components are depreciated and will soon be removed. If you are interest to work on web3 open source and love frontEnd i would love for you to help us build web3uiKit 2. I'll be rallying the troop soon

**Comment by Alvin-4550** [comment]
> you are not missing much @Alvin-4550 those components are depreciated and will soon be removed. If you are interested to work on web3 open source and are passionate about frontEnd i would love for you to help us build web3uiKit 2. I'll be rallying the troops soon

Thank you very much for answering my question so quickly. I really appreciate it. I am just a developer who has just started learning web3. I hope your project will be launched soon and I am looking forward to it

**Comment by BillyG83** [comment]
thanks @Alvin-4550 are you on our Discord? I will assemble a FE army there when we kick off V2
