### ISSUE TITLE
Button with text and icon

### ISSUE THREAD

**Issue by hookenful** [web3ui/web3uikit#1070]
Hi there, is it possible to combine icon and text on button? 

[Here](https://web3ui.github.io/web3uikit/?path=/story/2-forms-button--icon-button&args=text:assadasdasdas;size:xl;theme:custom;id:;type:reset;isFullWidth:true;loadingText:asdsadsadas) I don't see possibility to make this

**Comment by BillyG83** [comment]
of course my friend, check the `iconLayout` setting, currently it is set to `icon-only`

**Comment by BillyG83** [comment]
i'm going to close this issue now as i think i understood the issue. if i am incorrect please reopen and let me know. Thanks for using the kit, open source contributions are every welcome.

Please join our community on the [web3uiKit channel on Discord](https://moralis.io/discord)
