### ISSUE TITLE
Change font family for dropdown elements and background for modal

### ISSUE THREAD

**Issue by hookenful** [web3ui/web3uikit#1076]
Hi there!

You have a good UI kit to use

I have a couple of questions:
1) is it possible to chage default font family for dropdown elements ?
2) is it possible to change background color of modal? I mean not modal content area, but that is behind modal?

**Comment by BillyG83** [comment]
hey @hookenful thanks for using the kit and the feedback

1. the font family is very low level in the CSS so you should be able to set it globally in your app, like this

html
```
<body id="font">
```

css
```
#font * { font-family: serif }
```

2. Yes you can use the customise prop that a lot of the component now support, see this story

https://web3ui.github.io/web3uikit/?path=/story/5-popup-modal--custom-modal

let me know if you have any more question via our community on Discord please
https://moralis.io/discord
