### ISSUE TITLE
Update Moralis Discord Link in Readme

### ISSUE THREAD

**Issue by niteshseram** [web3ui/web3uikit#1079]
I think we might want to update the discord link in the readme of this project. It is taking me to some wrong discord server and it is misleading.

Just because of this, I was clueless about why I am not able to see any channel related to web3uikit 😆 

![image](https://user-images.githubusercontent.com/51370246/235200590-918b6bee-0126-4891-ae26-8dc21c599414.png)

**Comment by BillyG83** [comment]
nice, can you fix it @niteshseram 🙏

**Comment by niteshseram** [comment]
Closing this since it is fixed.

**Comment by BillyG83** [comment]
thanks @niteshseram I'm getting back to the kit and giving it some love in 2023. I appreciate your interactions 🥳
