### ISSUE TITLE
Cannot find module '@web3-ui/core' or its corresponding type declarations.ts

### ISSUE THREAD

**Issue by Kamasah-Dickson** [web3ui/web3uikit#1120]
I installed web3ui in my nextjs ts application and getting this error. I have tried installing the types for it but it seems there is nothing like that available. please resolve the issue

![Capture2](https://github.com/web3ui/web3uikit/assets/86136379/46f22ee3-ffda-4de7-8036-36571734095b)

I have web3uikit installed .

![Capture3](https://github.com/web3ui/web3uikit/assets/86136379/652051b3-456c-4a85-8287-be8a4018550f)

**Comment by BillyG83** [comment]
hey @Kamasah-Dickson the ConnectWallet is not in core, its in the web3 slice of the repo. but its also depreciated there is a work around but its not recommended. Please try MagicLink or RainbowKit
