### ISSUE TITLE
require$$13 is not defined

### ISSUE THREAD

**Issue by 7flash** [web3ui/web3uikit#114]
Hello team, I am trying to run a "hello world" project importing components from the library, but getting an error
Steps to reproduce:

```
git clone git@github.com:7flash/web3ui-hello-world.git
cd web3ui-hello-world
npm install
npm run start
```
Then this error shows up on localhost:3000

![image](https://user-images.githubusercontent.com/4569866/151419664-c2091f5d-d63c-4d77-83b2-9c6aab27642b.png)

**Comment by gat786** [comment]
I tried following the steps but I got a completely different error 
```
> challengedoapp@1.0.0 start /workspaces/web3ui-hello-world
> rollup -c rollup.config.js -w

[!] Error: Cannot find module '@babel/core'
Require stack:
- /workspaces/web3ui-hello-world/node_modules/@rollup/plugin-babel/dist/index.js
- /workspaces/web3ui-hello-world/rollup.config.js
- /workspaces/web3ui-hello-world/node_modules/rollup/dist/shared/loadConfigFile.js
- /workspaces/web3ui-hello-world/node_modules/rollup/dist/bin/rollup
```

Its probably due to how you are setting up rollup

**Comment by 7flash** [comment]
Well so what's the simplest way to start a project using this library?

**Comment by gat786** [comment]
@BillyG83 what would you suggest?

I personally think that a document describing how you create a project with web3uikit would be a nice addition to the project.

**Comment by 7flash** [comment]
I also tried parcel instead of rollup, but neither worked

**Comment by BillyG83** [comment]
hey @7flash and @gat786 

Try cloning the project, then `cd` into the project and run `yarn` and then `yarn storybook`. 

If you get stuck please checkout the Readme, Contribute and onboarding video.

I have to guess the -hello-world is because you forked the kit, right? TY guys

**Comment by 7flash** [comment]
Also tried preact, getting another error:

Can't resolve 'magic-sdk' in './node_modules/moralis/lib/browser/Web3Connector'

**Comment by gat786** [comment]
Have you tried it with Create-react-app? It works just fine over there :)
