### ISSUE TITLE
make a web3 version of recharts

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#166]
- make a chat component that can be used to replace recharts as used in the Moralis Admin `billingUsage/UsageChart`
- make an MVP and lets add features to it as we go

**Comment by vacekj** [comment]
I agree with the aim to have everything the devs need under one package/brand, but is this really necessary? Honestly I can't see any USP we would add on top of Recharts, it's already a very good library with great maintenance and features. I would let this one go until/if we feel like we could do something radically better. What are your thoughts?

**Comment by osamajandali** [comment]
@BillyG83 Any updates on this?

**Comment by BillyG83** [comment]
yeah i agree @vacekj its a huge undertaking and we have bigger fish to fry. TY @osamajandali
