### ISSUE TITLE
Build new Badge compoent

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#169]
This is a very simple component which will take two props:

1. Non optional text to display: string
2. Optional color / state prop: strings

Color / State:

- Blue / Normal (if unset)
- Green / Success
- Yellow / Warning
- Red / Danger

Remember that `<DemoComponent />` is there for you to copy and start hacking if you need it

**Comment by BillyG83** [comment]
<img width="446" alt="badge design" src="https://user-images.githubusercontent.com/13779759/156131837-70561b7e-6d09-46df-8fbc-b3269643bad2.png">

**Comment by BillyG83** [comment]
don't forget to use `styles/colors.ts`

**Comment by AbhinavMV** [comment]
Badge as in something like the below image?
![image](https://user-images.githubusercontent.com/35369843/156229333-2fcec0c3-20a8-449b-bd67-d72ff8059378.png)

or 
the "New" in the uploaded image?

> <img alt="badge design" width="446" src="https://user-images.githubusercontent.com/13779759/156131837-70561b7e-6d09-46df-8fbc-b3269643bad2.png">

If no one is working on this, I would like to give this a try 🙂

**Comment by locothedev** [comment]
> Badge as in something like the below image? ![image](https://user-images.githubusercontent.com/35369843/156229333-2fcec0c3-20a8-449b-bd67-d72ff8059378.png)
> 
> or the "New" in the uploaded image?
> 
> > <img alt="badge design" width="446" src="https://user-images.githubusercontent.com/13779759/156131837-70561b7e-6d09-46df-8fbc-b3269643bad2.png">
> 
> If no one is working on this, I would like to give this a try 🙂

Would love to see a Component from the community. So yes please go for it 👍

**Comment by AbhinavMV** [comment]
Thanks @locothedev 

> <img alt="badge design" width="446" src="https://user-images.githubusercontent.com/13779759/156131837-70561b7e-6d09-46df-8fbc-b3269643bad2.png">

I will go ahead with creating this type of component.
Will update soon. 
Btw if there is discord server for the community please share the link.

**Comment by locothedev** [comment]
> Thanks @locothedev
> 
> I will go ahead with creating this type of component. Will update soon. Btw if there is discord server for the community please share the link.

Sure we have the [#web3uikit channel](https://discord.gg/sF72YnPr) in our discord. This link expires in 1 day.

**Comment by BillyG83** [comment]
@AbhinavMV have a look at `<DemoComponent/>` ;)

made with love from developers =]

**Comment by AbhinavMV** [comment]
Thanks @BillyG83 , contribute.md was a really great resource, it had everything to easily understand the project. Also saw your video on YouTube was great.

Already created a PR #212 for this do check it out and let me know your thoughts 😄

**Comment by BillyG83** [comment]
completed by our friend @AbhinavMV
