### ISSUE TITLE
Discount Tag sizing

### ISSUE THREAD

**Issue by Y0moo** [web3ui/web3uikit#210]
Refactor sizing for the Discount type of Tag:
We need to switch from using prop `width`  to `size`. Size should be equal to width and height.
Also, it may be a nice idea to automatically calculate width and height depending on the content, but it may have unexpected sizing behavior

The behavior we have now:
![discountlabelbug](https://user-images.githubusercontent.com/78314301/156925783-e4512f98-c2b2-4324-b56e-415971504e87.gif)

**Comment by BillyG83** [comment]
<img width="397" alt="new settings for my bro" src="https://user-images.githubusercontent.com/13779759/157543342-857061d5-78a6-4b9b-8ade-9c75a89b74a5.png">

you like?
