### ISSUE TITLE
Typography documentation needs fixing

### ISSUE THREAD

**Issue by redhatt06** [web3ui/web3uikit#214]
Example code of Text and Copyable components in Typography are not correct. When show code is clicked it gives the following output:    
```
<NotificationProvider>
  <No Display Name />
</NotificationProvider>
```
It is also the same for the components in Notification docs.
Also I could not find any information about the "No" component. 

And when I click the copy icon it changes to check icon and never changes back to copy icon.

**Comment by BillyG83** [comment]
thanks for the feedback, lets try to summarise in bullet points if possible

- where / how did you get this? is it from our Storybook? please link if possible
```
<NotificationProvider>
  <No Display Name />
</NotificationProvider>
```

- You said _"It is also the same for the components in Notification docs."_ please elaborate or provide screenshot or links, its hard for me to fix this. TY!
- what is the No component?
- and for _"copy icon it changes to check icon and never changes back to copy icon."_ hey @dani69654 didn't you just add this feature?

**Comment by redhatt06** [comment]
> 

Hey Billy, sorry I should have been more clear.  Yes these are from the storybook. -> [https://web3ui.github.io/web3uikit/?path=/docs/4-ui-typography--copyable](url) I was able to figure these out from the example code of default components but I just wanted to mention this.

1.Typography
![image](https://user-images.githubusercontent.com/48768240/157073490-a886d1be-042b-4602-a803-84e2fa44bcd7.png)
2. Notifications
![image](https://user-images.githubusercontent.com/48768240/157073721-2557e6cd-db3b-4db8-8bfb-c819b4aee54b.png)

For the copy button  I was using an older version of the kit I have just tried it and it works.

Thanks keep up the good work!

**Comment by BillyG83** [comment]
TY @redhatt06 i just noticed this morning and you beat me to the punch! =]

**Comment by redhatt06** [comment]
You are welcome, i did nothing @BillyG83 . I wanted to write the codes for the storybook myself to help out. But couldn't figure out how to make this notification pop up with onClick(). Code here is typescript.
![image](https://user-images.githubusercontent.com/48768240/157350340-623fc87d-0c28-48b6-9f93-5b7f3d6e9a17.png)

**Comment by BillyG83** [comment]
sorry for the delay on this @redhatt06 our team is working super hard right now, your feedback is really valued TY
