### ISSUE TITLE
Stepper completeMessage issue

### ISSUE THREAD

**Issue by redhatt06** [web3ui/web3uikit#215]
completeMessage prop should be styleable. It is unusable with some background colors.  I have faced the same issue with large components like Form. Styling smaller parts of these components are either not possible or very difficult especially for css noobs like me :)

Also completeMessage could take html components like in stepData prop instead of only string it would be better since it gives more options.

**Comment by BillyG83** [comment]
TY for the feedback, lets try to summarise in bullet points for tasks if possible.

When you say _"It is unusable with some background colors"_ do you thinkit would better if Stepper and Form hard a white background by default?

**Comment by redhatt06** [comment]
Hi billy, 

No i think their backgrounds are perfect like this.  However, for example in my case the completeMessage is really hard to read and I want to change its color but I don't know how. -->
![image](https://user-images.githubusercontent.com/48768240/157078418-c85e5165-980f-4b46-935a-4027a29a8054.png)

I have change the completeTitle's color by doing something like this `.stepper h2{color: red;}` but it also changed the Form's h2 text which is also in my stepper. But i could not change the color of completeMessage from the css.

**Comment by BillyG83** [comment]
GM @redhatt06 did you see the fix i added for you?
https://github.com/web3ui/web3uikit/pull/248#issuecomment-1063365448

Its a quick fox for now but you can use the dynamic IDs to overwrite our styles with yours

```
#step-6 #stepper-title { color: white }
```
Thats if you have 5 steps, of course 😅
