### ISSUE TITLE
Create customizable Grid Element 

### ISSUE THREAD

**Issue by Y0moo** [web3ui/web3uikit#216]
The functionality we need:

Auto-sizing, gaps, size settings, changing positions(depending on the width of available space)

**Comment by osamajandali** [comment]
Hey @Y0moo 
What's our status on this ?

**Comment by BillyG83** [comment]
i'm going to close this for now. i will add this feature at some point but @Y0moo has enough on his plate... or should i say boilerplate? BOOM!
