### ISSUE TITLE
feature Skeleton

### ISSUE THREAD

**Issue by locothedev** [web3ui/web3uikit#219]
Lets add this super useful `Skeleton` component with variants such as `image` and `text` and `subtitle`

<img width="391" alt="Skeleton" src="https://user-images.githubusercontent.com/89942527/157063295-51a1dc58-d2c7-41e9-adf3-c01f62be5c53.png">

**Comment by AbhinavMV** [comment]
I am working on this. 
Please assign this to me @locothedev 😄

**Comment by locothedev** [comment]
@AbhinavMV you are about to become an industry legend my friend

**Comment by BillyG83** [comment]
@AbhinavMV welcome back my friend =]
