### ISSUE TITLE
Modal when scrolling should have a fixed footer and title

### ISSUE THREAD

**Issue by rayyan224** [web3ui/web3uikit#223]
When there is overflow, the footer and title of the modal should stay fixed. 

https://user-images.githubusercontent.com/62478924/157119818-cec5c6ee-1ef6-4acd-9fdf-e2802d095730.mov

**Comment by BillyG83** [comment]
do you think so? it would make me skip the modal content, so a user a primary button and they will press it, but i do get you it would be a nice feature. We would need the Modal header and footer to be fixed at perhaps 10vh / overflow hidden... then the content to be max height 70vh with overflow-y auto

**Comment by BillyG83** [comment]
anyone wants this? i put so rought CSS guides above, please add a `fixed mode` boolean property that is optional and set to false by default. So devs need to opt in. I think there is a no footer and maybe no header options to consider here also
