### ISSUE TITLE
Tooltip text line break

### ISSUE THREAD

**Issue by locothedev** [web3ui/web3uikit#235]
Seems like after each word there is a line break. Someone please fix that

![tooltipLine](https://user-images.githubusercontent.com/89942527/157413282-a789acd1-51b6-4279-beea-e7bcde05fac1.png)

**Comment by dani69654** [comment]
@rayyan224 @locothedev Should I work on this one?

**Comment by dani69654** [comment]
This does not seem to be a bug but rather a feature of tooltips. <br>
The tooltip property `content` type is declared as follow: `content: JSX.Element | string;` <br>
Following the example given in the tooltip stories, we can set the content as follow:

```js
 <span
            style={{
                width: '100px',
            }}
        >
            This is tooltip text
        </span>
```

In the example above, the width is set to `100px`.
