### ISSUE TITLE
BannerStrip + Button need margin

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#237]
<img width="540" alt="Screenshot 2022-03-09 at 12 05 34" src="https://user-images.githubusercontent.com/13779759/157429596-de8ffc22-1992-49ea-89b5-92fc27321821.png">

it looks too squashed, the padding on the button needs to come down or something to make it fit nicer. This is Button / colored / red /small

**Comment by avoajaugochukwu** [comment]
Can I take up this issue?

**Comment by AbhinavMV** [comment]
Will reduce padding on button and add some margin.
