### ISSUE TITLE
Documentation issue <ConnectButton />

### ISSUE THREAD

**Issue by gabkk** [web3ui/web3uikit#276]
The link provided in the documentation is broken

_Try the <ConnectButton /> component in the **[interactive documentation](https://web3ui.github.io/web3uikit/?path=/docs/web3-connectbutton--default)_**

**Current link**
https://web3ui.github.io/web3uikit/?path=/docs/web3-connectbutton--default

**Working link**
https://web3ui.github.io/web3uikit/?path=/docs/1-web3-connectbutton--default

**Comment by Y0moo** [comment]
Thank you @gabkk. Updated this one, but a lot of links in README needs to be updated after we renamed them #278 278
