### ISSUE TITLE
Incorrect links for stories in README

### ISSUE THREAD

**Issue by Y0moo** [web3ui/web3uikit#278]
After we updated the names of story categories and added numbers to them now a lot of links from README sends you to non-existing stories.

Example of incorrect link #276 

Task: check links in Readme and update them.

**Comment by BillyG83** [comment]
yeah this is my bad, I'll pick this out ASAP i really want to a lot to fix up our docs, they got left behind 😢

**Comment by osamajandali** [comment]
Fixed in #349
