### ISSUE TITLE
A way to use this toolkit inside an application without React

### ISSUE THREAD

**Issue by FazioNico** [web3ui/web3uikit#316]
Hi everyone!
I just discovered this UI kit and I can't find how to use it in an application that does not contain React...
I looked at the source code and, as an Angular advocate, I'm disappointed to see that all components are entirely designed with React library.
It could be a great idea  to choose a framework using Web Components which would have allowed any developper to use this UI kit. 
I use [StencilJS](https://stenciljs.com/) for component design as framework agnosic and I can help you with pleasure if you are considering a refactoring.

**Comment by locothedev** [comment]
Since the majority of web3 sticks to react refactoring to support other web frameworks is not on the roadmap. But we are keeping this mind once we go live with version 1.0 of web3uikit. Thanks!
@FazioNico

**Comment by BillyG83** [comment]
Yeah TY for the feedback @FazioNico 

I would love to build the entire library in OpenWC https://open-wc.org/ so it was totally framework free, and maybe we will some day in the future. But yeah like Loco said, the industry is using React and mainly its super fast and simple to build in React. TY for checking out our kit amigo

**Comment by FazioNico** [comment]
Thanks @BillyG83 @locothedev for your feedback. 
The UI Kit is very nice. I hope you will be more open in the future. 
I'll keep an eye out for updates.
