### ISSUE TITLE
Update Hero component with new features

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#328]
- allow user to align the content, left, center or right
- allow users to set curved edges to the Hero

to match this design please
https://www.figma.com/file/U8bUpFlNkqVyCmoB701Y3u/%5BDeveloper%5DMoralis-Dashboard-Design?node-id=7%3A1779056

**Comment by akinolu52** [comment]
solution [here](https://github.com/web3ui/web3uikit/pull/329)
