### ISSUE TITLE
Connect Button opens a modal overly inside my custom user menu 

### ISSUE THREAD

**Issue by fonko** [web3ui/web3uikit#346]
I was so happy when i saw this lib... but then I tried the connect button with its beautiful wallet selection popup and found out it was inflating itself inside my user's profile dropdown menu! :(

is there any way to fix this?

![error1](https://user-images.githubusercontent.com/2717577/161382093-4c00cda7-cb2d-45fe-8636-b2e4df0e7cd6.PNG)
![error2](https://user-images.githubusercontent.com/2717577/161382090-48ecf08f-ed16-49ab-bc96-fbe8d669235c.PNG)
![error3](https://user-images.githubusercontent.com/2717577/161382091-40ecb1f5-646f-4b47-a55e-023f7e0af4dc.PNG)

**Comment by Y0moo** [comment]
Hey @fonko, is the user's profile dropdown have "position: absolute" or made by portal?

**Comment by Y0moo** [comment]
Please install web3uikit@0.1.112-beta.0 and let me know how it works for you

yarn remove web3uikit
yarn add web3uikit@0.1.112-beta.0

**Comment by fonko** [comment]
> position: absolute

yes, it has: div (position absolute) -> div -> connect button

**Comment by fonko** [comment]
> Please install web3uikit@0.1.112-beta.0 and let me know how it works for you
> 
> yarn remove web3uikit yarn add web3uikit@0.1.112-beta.0

it didn't fix it. I had to take it out of the dropdown, if I use the button next to the avatar image (same level) it works.

![image](https://user-images.githubusercontent.com/2717577/161385384-a633572d-f039-4f4e-8822-132aaf5090b9.png)

**Comment by fonko** [comment]
Also, it would be great to be able to change buttons text on demand
I, for example, speak Spanish and the site we are building it is mainly for Spanish users

**Comment by Y0moo** [comment]
Could you share your Github repo with me to check?

**Comment by 0xPr0f** [comment]
@fonko 
https://github.com/web3ui/web3uikit/pull/496
This pull request should allow changing of button and modal text

**Comment by BillyG83** [comment]
yeah @fonko this seems like a simple CSS issue, please hit me with a link or a gitHub i can clone i bet i can fix this for you bud

**Comment by Lucienest** [comment]
@Y0moo facing the exact same issue, placed it on the bottom navigation bar 
```css
    zIndex: '100';
    position: 'fixed';
    bottom: '0';
    left: '50%';
    transform: 'translateX(-50%)';
```

**Comment by osamajandali** [comment]
Closing this for now as it seems the issue not related to the kit.
If the problems you facing still persists please feel free to re-open the issue and share with us the repo url so we can help you fix it.
