### ISSUE TITLE
Ledger Authentication

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#348]
this is internal issue, sorry dearest community! =]

all the info i have in pinned in Slack admin-fe

feel free to read up and ask questions on gitLabs but it will need to be part of @Y0moo 's component
https://web3ui.github.io/web3uikit/?path=/story/1-web3-walletmodal--default-wallet-modal

you can ask him questions, he is very friendly

**Comment by osamajandali** [comment]
Hey @locothedev what's our status on this ?

**Comment by locothedev** [comment]
@osamajandali for the feature. Moralis Sdk needs to have it implemented first

**Comment by BillyG83** [comment]
@locothedev can we close this for now? or do you have any work that might be lost... i dont see an MR. TY bro

**Comment by osamajandali** [comment]
Closing this for now
