### ISSUE TITLE
ToDo upgrades

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#351]
nice dude this is looking great so far. Can i ask for some small upgrades?

- when add it clicked please clear the input
- please use modern RTL testing, look for screen in test files for the newer way (this was my bad i should have been more clear sorry)
- add your component to the read me with nice gif etc like the others

otherwise this is perfect, nice job!

**Comment by akinolu52** [comment]
am i still supposed to test the stories if i'm using RTL? @BillyG83

**Comment by akinolu52** [comment]
![2022-04-05 18 40 52](https://user-images.githubusercontent.com/16763860/161817468-2eedf624-145c-40bb-afcf-67d8d946b1c7.gif)
