### ISSUE TITLE
useNotification hook positioning

### ISSUE THREAD

**Issue by ass77** [web3ui/web3uikit#391]
im having issue on using `useNotification()` hook  for position

```
const dispatch = useNotification();

  const handleNotifications = (type, message, title) => {
    dispatch({
      type: type,
![IMG_0966](https://user-images.githubusercontent.com/31248378/161874610-33b4e26b-a0a2-42c5-adb5-7d4e5c2fcb55.JPG)

      message: message,
      title: title,
      position: 'bottomL',
    });
  }
  ```

  
  As you can see I've already added `bottomL` but it still showing on top left + pushes all my components downwards. Im using nextjs by the way

**Comment by BillyG83** [comment]
thanks @ass77 

FYI @SmithVyne they posed this on Discord to help

![demo](https://user-images.githubusercontent.com/13779759/161921907-f027ebd3-2cf7-492e-b33f-b34d0d93f777.jpeg)

**Comment by SmithVyne** [comment]
> thanks @ass77
> 
> FYI @SmithVyne they posed this on Discord to help
> 
> ![demo](https://user-images.githubusercontent.com/13779759/161921907-f027ebd3-2cf7-492e-b33f-b34d0d93f777.jpeg)

Hi @ass77 I will be taking on this issue. I will tag you here If I have any questions about your current code setup.

**Comment by ass77** [comment]
Hey guys I managed to solved it by simply upgrade its version from `0.1.112` to 0.1.113` . It seems to be working as expected now. 
![ok](https://user-images.githubusercontent.com/31248378/161928935-f571357b-fc83-4564-abae-5dc1ea956843.JPG)

**Comment by SmithVyne** [comment]
Great @ass77 , again, you can reach out next time you run into something similar.

**Comment by BillyG83** [comment]
@ass77 we will close this for now. TY keep in contact =]
