### ISSUE TITLE
Export NFTCard

### ISSUE THREAD

**Issue by Ibcs16** [web3ui/web3uikit#398]
NFT card should be exported just like NFTCollection. This is good for cases where we want to use it separately.

**Comment by BillyG83** [comment]
hi @Ibcs16 thanks for the great suggestion. We would be happy to consider this feature for the web3uiKit. I was hoping maybe you could break down your idea a little more for us please? Maybe some bullet points and some screenshots would provide us with a 100% clear picture of what you need.

Also if you would consider to contribute your idea to the kit i would be happy to guide and help you, plus I will ask Kresimir to load up the Moralis Merch Catapult and aim it in your direction =]
