### ISSUE TITLE
Hero responsive

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#405]
could you make Hero a little nicer responsively? This may require a breakpoint to make the font a bit smaller..

- check z-index of gradient mode (see pic)
- maybe smaller font on mobile (see pic)
- need even padding top and bottom (see pic)
- make background url optional
- check the other stories of Hero on mobile too please, TY

![Screenshot 2022-04-08 at 12 59 41](https://user-images.githubusercontent.com/13779759/162423342-e7b9b678-ad2c-4b25-b6fb-e202af421879.png)

**Comment by BillyG83** [comment]
@akinolu52 for the padding one, maybe the height prop should set `min-height` so its more responsive?

**Comment by SmithVyne** [comment]
@BillyG83 @akinolu52 
Hi I wanna work on this task if you aren't already working on it.

**Comment by akinolu52** [comment]
Pls do @SmithVyne

**Comment by SmithVyne** [comment]
Cool!
