### ISSUE TITLE
Chain Selector - "Select All" button should become "Deselect All" if clicked 

### ISSUE THREAD

**Issue by dani69654** [web3ui/web3uikit#406]
As per design request, if the "Select All" button is clicked, it should become "Deselect All".

![Screenshot 2022-04-08 at 13 59 57](https://user-images.githubusercontent.com/60792849/162431342-9ede54a1-b434-4feb-a305-3010ce91788a.png)

**Comment by osamajandali** [comment]
I will take care of this

**Comment by BillyG83** [comment]
@osamajandali nice work bro TY for taking the initiative here

please remember to use the `in progress` label and make your branch wit the `Development` tab in the sidebar there so the task tracks your work TY. I will add this to the handbook actually
