### ISSUE TITLE
[TAB] - Design seems to be wrong

### ISSUE THREAD

**Issue by dani69654** [web3ui/web3uikit#447]
Let's double check the `Tab` component design. <br>
The selected choice seems to have a white bg:
![Screenshot 2022-04-13 at 16 39 46](https://user-images.githubusercontent.com/60792849/163205593-0908e6e6-1511-44cc-90e2-46ad4eeb57c3.png)

**Comment by rayyan224** [comment]
@dani69654 , just checked ur correct
