### ISSUE TITLE
Credentials Component in Mobile Screen

### ISSUE THREAD

**Issue by AbhinavMV** [web3ui/web3uikit#454]
In Mobile view, i need to scroll the component to view the hide and copy icon.
It would be better to make the icons fixed to right on mobile view and only keep the text scrollable.
Can be replicated in Google Chrome and Mozilla Firefox.

https://user-images.githubusercontent.com/35369843/163437374-cd614727-b0da-4e20-93f8-9f6d0b645bc4.mp4

If accepted i can work on this. 😄

**Comment by Y0moo** [comment]
Nice find!
If you will be able to make it like this it would be nice:

![image](https://user-images.githubusercontent.com/78314301/163439075-73e1f7bd-db56-42c6-8c44-1a28c6b36c90.png)

**Comment by Y0moo** [comment]
But also it can have more sense if we replace text dynamically with `https://xj5...:2053/servers`. Let's decide what is better for UX @BillyG83

**Comment by Y0moo** [comment]
Btw, splitting text like this can not be achieved with CSS, it's a JS func.

**Comment by AbhinavMV** [comment]
Cool will wait for Bill's decision. 🙌🏻 
`https://xj5...:2053/servers` even this much might overflow in mobile.
We could use `text-overflow: ellipsis` to clip the text. Much easier and won't need extra JS.

**Comment by Y0moo** [comment]
Yes, but `text-overflow: ellipsis` will make it `https://xj5...` - sometimes not the best for UX

**Comment by AbhinavMV** [comment]
Yeah good point.
Actually now that i think about ellipsis might not be the right approach
This component is used to display text(or hidden text) so hiding it default with ellipses would not be the desired result.

**Comment by BillyG83** [comment]
hi @Y0moo and @AbhinavMV good work here.

Yes it displays text but the ellipsis is the best fix i think, because users will want to see the text but will use the copy button in 99% of cases i think. So as long as we can show ellipsis but when they hit the copy button the full string is copied, that is perfect
