### ISSUE TITLE
Refactor Input component

### ISSUE THREAD

**Issue by osamajandali** [web3ui/web3uikit#460]
- Separate functionality and add add-ons on top it which allows more flexibility 
- Add more advance functionality

**Comment by DanielNgozika** [comment]
Hey @osamajandali, 

I see this is still in progress. Do the changes include an increase in height to reflect the size on Figma? https://www.figma.com/file/U8bUpFlNkqVyCmoB701Y3u/%5BDeveloper%5DMoralis-Dashboard-Design?node-id=5814%3A70623

**Comment by DanielNgozika** [comment]
Hey Abhinav,

I guess you don't know yet. A bunch of people were fired yesterday and I
was one of them. So...

**Comment by AbhinavMV** [comment]
New Issue is open for this -> #747
