### ISSUE TITLE
Modal with icon in title

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#462]
- make modal title match the design
- add optional icon to title to match design
- remove the joke button text is added, i didn't mean to push that 😅 

new design:
![Screenshot 2022-04-17 at 13 31 21](https://user-images.githubusercontent.com/13779759/163712549-dcd61351-39fd-400c-80f1-16f00b7134d9.png)

dumb button text
![Screenshot 2022-04-17 at 13 31 48](https://user-images.githubusercontent.com/13779759/163712553-9197202a-e184-438f-b655-f0ed099b2d68.png)

**Comment by BillyG83** [comment]
@locothedev says _"you can add custom jsx to modal title already but there is an odd thing. I tried to add typography but the modal seems to override the titles color to blue"_

**Comment by AbhinavMV** [comment]
Yeah i checked the code.
There is styling applied to h3 tag which changes the text color. 
I will try to change the styles according to the design given here 👍🏻
