### ISSUE TITLE
Verify Code component

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#463]
we need a new component for verifying codes:

Inputs
- sting for label text
- number for amount of inputs to render
- type for number or text versions
- onChange function that returns the values concatenated into a string (empty inputs are ignored)

check list
- [ ] Made from NewComp to ensure standardisation
- [ ] Has initial, focus, filled states like in design please
- [ ] Using modern RTL (see Accordion)
- [ ] [actions](https://storybook.js.org/docs/react/essentials/actions/) returning the value in Storybook
- [ ] killer DX

design
<img width="543" alt="Screenshot 2022-04-17 at 15 53 02" src="https://user-images.githubusercontent.com/13779759/163717596-87d5e58a-3d15-4032-b7bf-5681392f626f.png">

being used in context
![Screenshot 2022-04-17 at 15 43 28](https://user-images.githubusercontent.com/13779759/163717600-2f942833-adf3-4ff6-8c7b-6633fe8584bd.png)

**Comment by niklabh** [comment]
Is there figma available?
