### ISSUE TITLE
Fix Button small and outline goes green

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#469]
turn on small mode and outline mode and the button goes green, this should not happen obviously, please debug 🙏 

![Screenshot 2022-04-18 at 13 51 43](https://user-images.githubusercontent.com/13779759/163804703-89f8f3ca-331d-4353-b6d2-66121721b263.png)

**Comment by AbhinavMV** [comment]
![image](https://user-images.githubusercontent.com/35369843/163827182-cabe548a-faa6-47bc-824c-cd4c69dd29d9.png)

The current styling seems correct according to the Figma documentation. @BillyG83

**Comment by BillyG83** [comment]
> ![image](https://user-images.githubusercontent.com/35369843/163827182-cabe548a-faa6-47bc-824c-cd4c69dd29d9.png)
> 
> The current styling seems correct according to the Figma documentation. @BillyG83

this has changed a lot since i saw it 🤯  i need to refactor Button
