### ISSUE TITLE
TODO: Rename Radios props and logic

### ISSUE THREAD

**Issue by rayyan224** [web3ui/web3uikit#473]
Re-name radio props to better names. 
For example 
`setWhichIsChecked?: number;
`
should be named defaultSelectedIndex.

Also, Radios should be done as such. This is because Radios are a native element and should not hold a state.

```
<Radio.group>
     <Radio></Radio>
</Radio.group>
```

These are breaking changes and should be done in v2.

**Comment by BillyG83** [comment]
hey @rayyan224 and @SmithVyne there is quite a lot of 'human friendly' text like this in the kit, my idea was to make the features as easy to understand as possible and while i do agree you named it better, is it worth pushing a breaking change for?

**Comment by BillyG83** [comment]
then i just saw the V2 label, i get what you mean now that this could be a feature change, bare in mind we are not even in V1 yet 😅

**Comment by BillyG83** [comment]
ok if there is no discussion i will close this, you guys can reopen if you want to talk more about this but it seems like a breaking change we don't need right now
