### ISSUE TITLE
Pricing Plan Card does not much designs

### ISSUE THREAD

**Issue by rayyan224** [web3ui/web3uikit#477]
Current Design:
![Screen Shot 2022-04-19 at 9 56 21 AM](https://user-images.githubusercontent.com/62478924/164022075-9585f4a8-df9c-4687-b7d7-a3c9ced72dda.png)

Design from Figma
![Screen Shot 2022-04-19 at 9 56 35 AM](https://user-images.githubusercontent.com/62478924/164022153-fd1ab880-d320-4bc1-8d49-9d0c78020641.png)

Let's make another component, called a PlanCard that handles this specifically so we can nail the design.

**Comment by BillyG83** [comment]
nice task @rayyan224 TY for adding

The Card needs to
- be green border if isActive
- disabled button if isActive
- each should take an ID 'free', 'starter' or 'pro'
- takes array of strings for checkmarks
- onClick returns upgrade + ID or downgrade + ID
