### ISSUE TITLE
Input add description option

### ISSUE THREAD

**Issue by rayyan224** [web3ui/web3uikit#488]
<img width="834" alt="Screen Shot 2022-04-25 at 6 25 55 PM" src="https://user-images.githubusercontent.com/62478924/165184918-590cb369-aa75-4434-89ae-98e7dd0de65a.png">

- Add Description Prop
- Should Not Show if component is in error state

**Comment by Y0moo** [comment]
https://github.com/web3ui/web3uikit/issues/478
