### ISSUE TITLE
[CodeArea] Add Sizing functionality

### ISSUE THREAD

**Issue by Y0moo** [web3ui/web3uikit#494]
- Add button "Full-size"
- Solve the problem with displaying the default HTML resizer
- Add ability to set max height(for example 60vh)
![image](https://user-images.githubusercontent.com/78314301/165225240-6fa21dbf-b329-4c7c-8f30-248fdd59a699.png)

**Comment by BillyG83** [comment]
hide a resizer using `::webkit-resizer { display: none};`
