### ISSUE TITLE
[Input] Style update + description

### ISSUE THREAD

**Issue by Y0moo** [web3ui/web3uikit#498]
We have updated the design for the `<Input />`

Task:

- Update the design for the Error message
- Add a description below the Input
- Make sure the bottom fields don't overlap each other and make a bottom gap.

![image](https://user-images.githubusercontent.com/78314301/165276645-d2180657-17b5-441e-8714-01cfd760de4d.png)

![image](https://user-images.githubusercontent.com/78314301/165276603-cf8aa89d-bbb2-4fc3-a192-54b8af277a90.png)

**Comment by BillyG83** [comment]
update from design

<img width="790" alt="image" src="https://user-images.githubusercontent.com/13779759/165315212-b014e540-3009-4f54-b095-4871cd365570.png">
