### ISSUE TITLE
[Documentation] - Wrongs StoryBook Docs for Modal Component (No Footer)

### ISSUE THREAD

**Issue by dani69654** [web3ui/web3uikit#509]
Url: https://web3ui.github.io/web3uikit/?path=/docs/5-popup-modal--no-footer

As developer, I do expect to see the prop `hasFooter={false}` in the docs.

**Comment by SmithVyne** [comment]
Hi, I am taking this issue. Is this really an issue? @BillyG83

**Comment by Darrellbor** [comment]
@dani69654 can i get some insight into this issue

**Comment by BillyG83** [comment]
i think he means on [this story](https://web3ui.github.io/web3uikit/?path=/docs/5-popup-modal--no-footer#no-footer) is expecting that Sotrybook will show the prop when he clicks 'show code' button. is that right @dani69654 ?

![Screenshot 2022-05-10 at 12 54 33](https://user-images.githubusercontent.com/13779759/167613012-840f84c1-8603-40ee-8588-404ef75b767a.png)
