### ISSUE TITLE
[CodeArea] min-height prop

### ISSUE THREAD

**Issue by Y0moo** [web3ui/web3uikit#513]
What do we have now: 

![image](https://user-images.githubusercontent.com/78314301/165763860-30ebc5a0-d53c-4b80-a7a2-34dc83604835.png)

What do we want:

![image](https://user-images.githubusercontent.com/78314301/165763985-90dd488f-a920-4f04-a0f9-7ecb19b84eae.png)

**Comment by BillyG83** [comment]
hey @Y0moo can @SmithVyne do this for you?

**Comment by BillyG83** [comment]
hey @SmithVyne include this task in here too please
https://github.com/web3ui/web3uikit/issues/494

**Comment by Y0moo** [comment]
it was added in https://github.com/web3ui/web3uikit/pull/515

**Comment by BillyG83** [comment]
close by #515
