### ISSUE TITLE
[Checkbox] label out of sync with design

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#535]
## Summary

The "Enabled" label is different from Figma

## Steps to reproduce

- Clone the repo
- Switch to the branch `113-historical-sync-settings/molecule`
- Run storybook

## What is the current bug behavior?

The font color is #68738D with 16px

## What is the expected correct behavior?

The font color should be #041836 with 18px

## Relevant logs and/or screenshots

see design file, the link is in the FE Handbook

**Comment by BillyG83** [comment]
just FYI we never hardcode colors so `#68738D` should be in `colors.js` if not add it please

**Comment by SmithVyne** [comment]
@DanielNgozika can I take this task?

**Comment by DanielNgozika** [comment]
> @DanielNgozika can I take this task?

Hey man, I've already handled it.

**Comment by SmithVyne** [comment]
No problem
