### ISSUE TITLE
Allow implicit properties

### ISSUE THREAD

**Issue by oscario2** [web3ui/web3uikit#550]
Include remaining properties like [...props](https://github.com/web3ui/web3uikit/blob/master/src/components/Input/Input.tsx#L42) for each component to allow passing of implicit properties such as `data-*` to ease e.g e2e testing.

**Comment by BillyG83** [comment]
nice @SmithVyne please keep @oscario2 informed when you complete

**Comment by SmithVyne** [comment]
Yeah 🚀 🚀
