### ISSUE TITLE
[Credentials] Doesn't rerender after updating text prop

### ISSUE THREAD

**Issue by Y0moo** [web3ui/web3uikit#562]
The component doesn't rerender after updating the text prop.

The buggy behaviour comes from here: https://github.com/web3ui/web3uikit/blob/257363fa3cabbcd1bd481f250cabf483e1376800/src/components/Credentials/components/TruncateString.tsx#L98

**Comment by Y0moo** [comment]
Storybook Demo: https://web3ui.github.io/web3uikit/?path=/story/2-forms-credentials--with-title-and-icon

**Comment by AbhinavMV** [comment]
Nice catch, will raise a PR soon 🙌🏻
