### ISSUE TITLE
[Input]: Implicit props passed to wrapper as well

### ISSUE THREAD

**Issue by oscario2** [web3ui/web3uikit#572]
This could apply to more components then just the `<Input>` but as of https://github.com/web3ui/web3uikit/issues/550 

The `<Input>` is wrapped in a `<DivStyled>` which also passes along [the implicit properties](https://github.com/web3ui/web3uikit/blob/master/src/components/Input/Input.tsx#L121) resulting in this

```html
<div data-e2e="auth-input-email">
  <input data-e2e="auth-input-email" />
</div>
```

As much as a selector can be narrowed down by the element. This would become an issue if people were to pass say any prop or listener from e.g  `HTMLProps<HTMLInputElement>` implicitly as said property would attach to both elements

**Comment by Darrellbor** [comment]
Hello @oscario2, 
Are we looking for a scenario were the props are only spread to input or a scenario where it knows whether to pass it to the div wrapper or input element?

**Comment by oscario2** [comment]
In this case just pass it to the actual component (input in this case) as that's what you would assume to have the prop/listener. I'm open to suggestions if anyone else would see use cases of passing the props to the wrapper as well though

**Comment by Darrellbor** [comment]
@oscario2 I completely understand that, although what if you want to modify the wrapper with properties not defined in the prop list

**Comment by oscario2** [comment]
@Darrellbor Generally I don't think we'd want people passing other implicit props than like `data-*` which mostly would concern the actual component but you are free to make a solution which allows passing to the wrapper and/or component if you'd like.

**Comment by Darrellbor** [comment]
@oscario2 I thought it through and I think you're right about that, so I implemented it such that implicit props only affect the component, must modifications to the wrapper happen within the component, and if ever outer, it’ll mostly be style-based changes which are catered for.
