### ISSUE TITLE
How to use different bg color, text and border style for ConnectButton?

### ISSUE THREAD

**Issue by Tingwei-Justin** [web3ui/web3uikit#589]
Hi,

How can I use different bg color, text and border style for ConnectButton?

<img width="202" alt="image" src="https://user-images.githubusercontent.com/33661382/168453555-e71f5f0a-11ab-43bf-a3a6-b4973e7c1ee6.png">

**Comment by BillyG83** [comment]
hi @Tingwei-Justin thanks for the question.

In a future update we plan to make the web3uiKit components more customisable with the ability to theme your kit elements. But currently I would advice you use good old HTML & CSS

HTML
```
<div id="billsButton">
  <ConnectButton />
</div>
```

CSS
```
#billsButton button {
  background-color: red;
}
#billsButton hover {
  background-color: blue;
}
```

I hope this helps bud, else you can reach us on Discord
