### ISSUE TITLE
Usage example fails

### ISSUE THREAD

**Issue by Huge** [web3ui/web3uikit#604]
The code under https://github.com/web3ui/web3uikit#-usage fails with missing properties error. Also probably hinting to put it into `src/App.tsx` would help newbies.
See https://discord.com/channels/819584798443569182/932913723503431680/977130028187926558

**Comment by Y0moo** [comment]
Thank you @Huge! 

The example is not full actually, there are some required props missing. Will update the tutorial ASAP.
