### ISSUE TITLE
FEATURE REQUEST: Send Transaction Button

### ISSUE THREAD

**Issue by PatrickAlphaC** [web3ui/web3uikit#605]
I think it would be awesome if there was a component that looks like this:

```
import {sendTransactionButton} from "web3uikit"
.
.
.
<sendTransactionButton runContractFunction={doTx} useNotification={true}/>
```

And it take a `runContractFunction` object from the `react-moralis` `useWeb3Contract` as an input parameter, and then does the following:

1. Has a spin & disabled animation when metamask is poped up
2. Has a spin animation as the transaction is going through
3. stops spinning when the transition has 1 block confirmation, and optionally a `useNotification` pops up

I think this would save lot of development time, and would be so sick. We'd have like a `useState` and `useEffect` in this component tracking the status of the transaction. 

Let me know what you think.

**Comment by BillyG83** [comment]
hey @PatrickAlphaC would you like to collaborate on this? I will make the UI, tests, styles, everything, if you can push a standard HTML button that does what you want. How does that sound?

**Comment by PatrickAlphaC** [comment]
@BillyG83 what do you mean?
> if you can push a standard HTML button that does what you want

**Comment by AbhinavMV** [comment]
Hey @PatrickAlphaC , what bill is trying to say is :
You can create a PR, with a new button component which on click, would send a transaction. (Basically the feature you have in mind 😄)
Don't worry about styling, sending notification, tests....etc we will take care of that 🙌🏻 
Thank you for taking an interest in the kit 😄 
Feel free to connect with us on moralis discord if you have any queries
@BillyG83 correct me if i am wrong 🙌🏻

**Comment by AbhinavMV** [comment]
Hey @PatrickAlphaC 
TY for this idea ❤️ 
This is added to our new monorepo. Give it a try and let us know what you think 🙌🏻 

Install :  `yarn add @web3uikit/web3`

You can give it a try [here](https://web3ui.github.io/web3uikit/?path=/story/1-web3-sendtransaction--example-purchase-candy)

Closed by #745

**Comment by PatrickAlphaC** [comment]
Sorry! Totally missed the comms here. YES! Will try it now.

**Comment by PatrickAlphaC** [comment]
I'm not sure how to use this, any chance we can update the docs? 

```javascript
import { Web3Initialize } from "@web3uikit/web3"
```

I'm getting:

```
Module '"@web3uikit/web3"' has no exported member 'Web3Initialize'.ts(2305)
```

**Comment by AbhinavMV** [comment]
Hey @PatrickAlphaC 
Sorry for the delay.
Component name is - `SendTransaction`
Checkout our storybook, now the docs are updated - https://web3ui.github.io/web3uikit/?path=/docs/1-web3-sendtransaction--example-purchase-candy
Please install package version - 0.1.5

**Comment by PatrickAlphaC** [comment]
Nice! Closer... 

My button is greyed out for some reason... ?

```javascript
<SendTransaction
                        chainId={chainIdHex as chainIdType}
                        contractOptions={{
                            abi: abi,
                            contractAddress: raffleAddress!,
                            functionName: "enterRaffle",
                            params: {},
                            msgValue: entranceFee,
                        }}
                        buttonConfig={{
                            text: "Enter Raffle",
                            theme: "primary",
                        }}
                        notificationConfig={{ dispatch }}
                    />
```
<img width="714" alt="Screen Shot 2022-08-12 at 11 44 01 PM" src="https://user-images.githubusercontent.com/54278053/184467232-a36f87ed-506a-4766-8fbd-f40feccfd700.png">

Even if I change the disabled prop:

```
disabled: false,
```

**Comment by AbhinavMV** [comment]
@PatrickAlphaC 
This component needs a moralis server. make sure your server is active.
If server is active, could you share the github link to code or abi and contract address?
Component seems to be working for my sample contract 😅

**Comment by PatrickAlphaC** [comment]
Why does it need a Moralis server?

I think that's something that shouldn't be required.

**Comment by AbhinavMV** [comment]
Did a bit of research and looks like it does not need the server.
Will make the necessary changes and create a PR soon meanwhile you can use the component with the server 😄 
Thanks a lot @PatrickAlphaC 🙌🏻
