### ISSUE TITLE
[Fix]: Tooltip active on hover it's content

### ISSUE THREAD

**Issue by Darrellbor** [web3ui/web3uikit#622]
When the tooltip is not active and you scroll over where the content is supposed to be it becomes active.
Fix should only allow the target element to activate the tooltip.

**Comment by osamajandali** [comment]
Go for it @Darrellbor 🚀
Would be nice if you add screenshot, if possible, to the description and add as well steps to reproduce so that will help the future reviewer of you PR

**Comment by Darrellbor** [comment]
> Go for it @Darrellbor 🚀 Would be nice if you add screenshot, if possible, to the description and add as well steps to reproduce so that will help the future reviewer of you PR

Thanks i will do that

**Comment by Darrellbor** [comment]
https://www.loom.com/share/72d448ca1b6b4c4d83aabf117911b86e

More context and steps to reproduce
