### ISSUE TITLE
Create Upload component

### ISSUE THREAD

**Issue by Y0moo** [web3ui/web3uikit#629]
FIGMA: https://www.figma.com/file/lENHKVkCjdfZXfFLv5T2Yn/Moralis-UI-Kit?node-id=9868%3A52358

Two themes for `theme` prop: `textOnly` and `withIcon`

```<Upload theme="textOnly" />```

![image](https://user-images.githubusercontent.com/78314301/171398377-ae4c9fbd-d17b-40c9-b686-61f43ce6c887.png)

**Comment by AbhinavMV** [comment]
closed by #647
