### ISSUE TITLE
[Code generator] Plop integrating

### ISSUE THREAD

**Issue by Y0moo** [web3ui/web3uikit#650]
To boost DX and keep the code standardized we should integrate the code generator library "Plop".

**Comment by BillyG83** [comment]
![Screenshot 2022-06-16 at 17 11 51](https://user-images.githubusercontent.com/13779759/174102136-283f5bac-0de5-4b52-9ba8-323252750d5f.png)

hey @Y0moo please open your branch from the ui in each task, then it will auto close the issue

**Comment by AbhinavMV** [comment]
Closed by #652 
Required changes for this made in monorepo as well :raised_hands:
