### ISSUE TITLE
[Icon] add Title prop

### ISSUE THREAD

**Issue by Y0moo** [web3ui/web3uikit#654]

**Comment by BillyG83** [comment]
oh wait this is close, my bad

**Comment by BillyG83** [comment]
no wait again, its merged but not closed... i'm confused @Y0moo =]

**Comment by AbhinavMV** [comment]
Title prop is being added in the monorepo
We will have individual logos in v2. i.e -> `<Icon svg='ada'/>` will be used like `<Ada />`
Also we will be using svgr to create icons from svg files rather making it ourselves 🙌🏻 
Closing this for now #655
