### ISSUE TITLE
Table Component Missing row click prop

### ISSUE THREAD

**Issue by rayyan224** [web3ui/web3uikit#658]
Requested feature: 
Table Component should have a row click prop

Current workload:
OnClick on all cells we render as data

**Comment by BillyG83** [comment]
HEY @rayyan224 can you add some more detail here and maybe a screenshot as i guess you saw this in the design, right? TY dude

**Comment by rayyan224** [comment]
Basically, we want a prop call on RowClick, that callback when any cell in a particular row is clicked.
