### ISSUE TITLE
[Link To] Icon not aligned 

### ISSUE THREAD

**Issue by dani69654** [web3ui/web3uikit#661]
It seems that the icon shown in the `LinkTo` component is not aligned, also I would love to have an option to remove the icon itself
![Screenshot 2022-06-21 at 13 40 56](https://user-images.githubusercontent.com/60792849/174790944-b629feef-e517-4d7f-b9d9-5f0f9171ca91.png)

**Comment by AbhinavMV** [comment]
Closed by #683
