### ISSUE TITLE
Wallet Connect Modal Not Working?! [Vite / Replit / TSX] 

### ISSUE THREAD

**Issue by Shinixagami** [web3ui/web3uikit#673]
This Components Wallet Connect Features does not work. 
[Link](https://web3ui.github.io/web3uikit/?path=/docs/1-web3-walletmodal--default-wallet-modal)

---------------------------------------------
![image](https://user-images.githubusercontent.com/53989590/175821371-eb6ddd88-f28d-4538-a080-c8a1a5b0c70d.png)
The Components Docs looks like this & I wished they also had detailed documents on the modal. Its just blank & most people ignore the Wallet Connect Option usually using MetaMask. 

Main Problem:
-No docs on Wallet Modal 
-Wallet Connect Pop-Up not showing
-This might also apply to other components providers like Trust Wallet. 

Details:
-No issues pop-up on console
+I am using just the modal itself & calling it via my own button 
+This issue also applies to the "ConnectButon" component which is used to call the modal.
+Hosted on Replit (Boosted)
+Uses TypeScript (TSX) -superscript to JSX react. They have no dif. 
+Moralis Server
+Metamask is the only button that works (Probably because its native to most browsers & moralis)

Dependencies Installed:
+Vite
+React-Moralis
+Moralis
+Web3UiKit  
+Ethers

Take a look at these documents from Web3Modal which is very similar (Which Web3UIKit should built upon.)
[Link](https://github.com/Web3Modal/web3modal)

Suggestions:
Web3Modal from Wallet Connect is cool -I wish they had the same docs that Web3UiKit has, I also wish it had more robust settings -as I want to be able to pick the Modals Providers & change more things on it. Its the gateway to web3, this should definitely be improved.

**Comment by TaiyangAh** [comment]
same , just 2 days ago it works when I click Metamask option , btw I use create-react-app

**Comment by zihangg** [comment]
+1, can't find any documentation as to how to actually utilize the WalletModal.

**Comment by alexnguyennz** [comment]
This seems to be related to the use of Vite which also doesn't play well with react-moralis e.g. https://github.com/MoralisWeb3/react-moralis/issues/228 or https://github.com/MoralisWeb3/react-moralis/issues/229. Other providers like Web3Auth also do not work in a new Vite/React project (but both will work fine in a regular Create-React-App/webpack project).

@zihangg [You can check out the props for WalletModal here](https://web3ui.github.io/web3uikit/?path=/docs/1-web3-walletmodal--default-wallet-modal).

**Comment by BillyG83** [comment]
thanks for the feedback @Shinixagami @TaiyangAh @zihangg @alexnguyennz 

i dont supposed any of you have a proposed solution or could help out here? Else we will pick this up soon but it could be a week to two as the team is very small and it is holiday season, sorry

**Comment by AbhinavMV** [comment]
Hey @Shinixagami , @TaiyangAh , @zihangg , @alexnguyennz 
TY for using the kit. ❤️ 
Like @alexnguyennz mentioned in the above comment, this seems to be an issue with vite.
Wallet connect is not getting bundled with Vite. Please check out this solution - https://stackoverflow.com/questions/71067299/walletconnect-fails-to-get-bundled-with-vite

Wallet connect is working correctly in our storybook(It is bundled with webpack5). Checkout - https://web3ui.github.io/web3uikit/?path=/story/1-web3-connectbutton--default
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/35369843/178999952-5d315b10-72dd-4385-b116-d4081d97007c.png">

**Comment by BillyG83** [comment]
I am closing this issue as soon this section of the repo will be depreciated so no further developed should be expected. Thanks

If you have questions please reach out to me on Moralis Discord
