### ISSUE TITLE
feature: Working on ENSAvatar

### ISSUE THREAD

**Issue by 3scava1i3r** [web3ui/web3uikit#688]
Overview:
ENS or Ethereum Naming Service has avatars attached to the addresses on mainnet. Instead of just using blockie we can have this as an avatar in web3uikit

What I would build:
I would integrate  ENSAvatars as a component to be used as a basic avatar if they have one and have blockies as a backup if the consumer does not have an ENS Avatar.This can be an image or a gif.for example vitalik.eth gives this gif:
![image](https://user-images.githubusercontent.com/52003051/176709923-d4d44325-3268-49ed-8f93-7264f3530669.png)

Reference:
- https://ensdomains.github.io/ens-avatar/
- https://docs.ens.domains/ens-improvement-proposals/ensip-12-avatar-text-records

**Comment by AbhinavMV** [comment]
Closed by #689
