### ISSUE TITLE
Solana NFT & NFTBalance Component

### ISSUE THREAD

**Issue by YosephKS** [web3ui/web3uikit#690]
Currently no love for Solana? 💔

But seriously, it definitely will be very nice to have some similar `NFT` and `NFTBalance` component just like what we have for ethereum 🙌🏼 

Cheers 💚

**Comment by 3scava1i3r** [comment]
@YosephKS Thank you for the wonderful suggestion, I would surely like to work on something like this

**Comment by 3scava1i3r** [comment]
@AbhinavMV do you mind assigning me this?

**Comment by YosephKS** [comment]
@3scava1i3r any updates on this task?

**Comment by 3scava1i3r** [comment]
Working on this we had a monorepo change and i was working on one hackathon should be do soon

**Comment by YosephKS** [comment]
okok fantastic! 🔥

**Comment by BillyG83** [comment]
I am closing this issue as soon this section of the repo will be depreciated so no further developed should be expected. Thanks

If you have questions please reach out to me on Moralis Discord
