### ISSUE TITLE
docs: correct yarn install in contribute.md

### ISSUE THREAD

**Issue by janvinsha** [web3ui/web3uikit#691]
The correct code for installing yarn in the docs is `yarn` but should be `yarn install`

**Comment by BillyG83** [comment]
hey @janvinsha thanks for taking an interest in the kit and TY for providing us feedback

Basically `yarn` == `yarn install` notice i did not use === 😉 

you can read more here:
https://stackoverflow.com/questions/59265231/what-is-the-difference-between-yarn-and-yarn-install

Also we are just about to go to v1 and use a mono repo and `pnpm` so if you want to open an PR to fix this you can and i will thank you for it. But i don't think it is needed right now.

Thanks friend, have a great day and keep building web3 😁

**Comment by BillyG83** [comment]
great job @janvinsha 
closed by #692
