### ISSUE TITLE
[Icon] check all icons that are in the kit fimga are present in the kit

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#693]
we are for sure missing this one, and i think more like and upload icon for the new Upload component

![stop](https://user-images.githubusercontent.com/13779759/176872827-94d9e2a0-f1fe-4476-88d8-4e636e97d747.svg)

## Stretch goal

it would be cool to have one story where all the icons are shown in a grid with their name handy to copy and paste

**Comment by AbhinavMV** [comment]
@BillyG83 Please don't close this yet.
I think I only completed the stretch goal 🤣 .
Did not find the upload icon in Figma.

**Comment by AbhinavMV** [comment]
Closed by monorepo #659
