### ISSUE TITLE
Solana Logo Ugly on Button  🥺

### ISSUE THREAD

**Issue by YosephKS** [web3ui/web3uikit#694]
Solana logo on `Button` no bueno!

<img width="180" alt="Screen Shot 2022-07-01 at 18 31 43" src="https://user-images.githubusercontent.com/48710170/176889606-c2e7c2f3-8e4a-4afe-bda8-3202fee0ed13.png">

**Comment by AbhinavMV** [comment]
Thankyou @YosephKS for using our kit and letting us know about this issue. 
This is fixed and will be added in the next release.
Closing this issue now 🙌🏻  #697
