### ISSUE TITLE
feature: Working on BlockNumber Component

### ISSUE THREAD

**Issue by 3scava1i3r** [web3ui/web3uikit#695]
Overview:
I went to various dapps like a uniswap and always saw a blocknumber component in the footer or something so i thought why not add this here.Added an image for reference

![gvg](https://user-images.githubusercontent.com/52003051/176967759-99499ce9-88a2-422e-95b3-1da2199d526e.png)

What I would build:
i would make a small BlockNumber component currently just functional to show the current blocknumber of any evm compatible chain using ethers.

**Comment by AbhinavMV** [comment]
Closed By #696
