### ISSUE TITLE
feature : adding support for ipfs/normal file uploading component

### ISSUE THREAD

**Issue by 3scava1i3r** [web3ui/web3uikit#707]
Overview:
Its just a small component to upload any file to moralis or ipfs using moralis.I personally use ipfs for a lot of my nft projects so making a component like this would be great

 
What i'll do:
- Make an input component for addition of files
- Use moralis hooks to add upload support for basic moralis and ipfs

**Comment by AbhinavMV** [comment]
closed by 708
