### ISSUE TITLE
feature: enable onHover on PopoverElement to show a tooltip

### ISSUE THREAD

**Issue by dani69654** [web3ui/web3uikit#716]
**Issue:** Currently, admin has this dropdown:
<img width="133" alt="Screenshot 2022-07-11 at 10 22 52" src="https://user-images.githubusercontent.com/60792849/178220737-0251d05f-e206-4831-91ab-055349db381a.png">

**Code:**

```tsx
 <PopoverDropdown
      parent={<Avatar theme="image" isRounded size={36} />}
      position="bottom"
      moveBody={-75}
    >
      <PopoverElement
        text="Account Settings"
        icon={iconTypes.cog}
        width={150}
        onClick={() => {
          href(`/account/profile`);
        }}
      />
```

**Request:**
Design wants:
<img width="332" alt="Screenshot 2022-07-11 at 10 23 50" src="https://user-images.githubusercontent.com/60792849/178220912-d6258381-7de5-4be3-9498-3322359822cb.png">

On hover, we should display a tooltip with a list of teams

**Comment by AbhinavMV** [comment]
closed by #718
