### ISSUE TITLE
Module not found: Can't resolve 'lodash.merge'

### ISSUE THREAD

**Issue by Hrugved** [web3ui/web3uikit#723]
I got this error only after installing `yarn add web3uikit`. maybe some dependency version issues?

**Command**: `yarn dev`
**Output**: 
```
yarn run v1.22.15
warning ../package.json: No license field
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - SWC minify release candidate enabled. https://nextjs.link/swcmin
error - ./node_modules/@toruslabs/http-helpers/dist/httpHelpers.esm.js:2:0
Module not found: Can't resolve 'lodash.merge'

Import trace for requested module:
./node_modules/@toruslabs/openlogin/dist/openlogin.esm.js
./node_modules/@web3auth/web3auth/dist/web3auth.esm.js
./node_modules/moralis/lib/browser/Web3Connector/Web3AuthConnector.js
./node_modules/moralis/lib/browser/MoralisWeb3.js
./node_modules/moralis/lib/browser/Parse.js
./node_modules/moralis/index.js
./node_modules/react-moralis/lib/index.esm.js
./pages/_app.js

https://nextjs.org/docs/messages/module-not-found
```

**tried :**

- `yarn add lodash.merge` 
- reinstalling node_modules

**package.json**
```
{
  "name": "dapp-lottery",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "moralis": "^1.9.0",
    "next": "12.2.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-moralis": "^1.4.0",
    "web3uikit": "^0.1.169"
  },
  "devDependencies": {
    "eslint": "8.19.0",
    "eslint-config-next": "12.2.2"
  }
}
```

mac
node `v16.16.0`
npm `8.11.0`
yarn `1.22.15`

**Comment by AbhinavMV** [comment]
Hey @Hrugved 
TY for using our kit.
There does not seem to be any dependency issue in the kit. 
I created a next.js project and installed the exact same dependency as yours and it is working for me.
Steps followed:
1. npx create-next-app next-app
2. cd next-app
3. yarn add moralis react-moralis web3uikit
4. yarn dev
<img width="980" alt="image" src="https://user-images.githubusercontent.com/35369843/178997837-b881c183-4757-45eb-a00f-09329294c8a3.png">

Could you try deleting your node_modules folder and try again?
If you can share repo link that would be great too 😄

**Comment by Hrugved** [comment]
repo: https://github.com/PatrickAlphaC/nextjs-smartcontract-lottery-fcc
the issue seems to be with yarn. `npx create-next-app@latest --use-npm` to create project and it seems to work now.

**Comment by AbhinavMV** [comment]
Glad to hear its fixed 🙌🏻 
TY for using the kit. 👷🏻
