### ISSUE TITLE
Fix the country combobox in the Payment options to allow search countries by letter

### ISSUE THREAD

**Issue by MateusbrMedeiros** [web3ui/web3uikit#728]
**Summary**

The countries combobox needs to have a search by letter to turn things easier to the user search his/her own country.

**Steps to reproduce**

- Go the Plan and Billing
- Add New Card
- Click in the Country combobox

**Actual Behaviour**

It's not possible to search countries by the letter

**Expected Behaviour**

The user should be able to search countries by the letter.

![image](https://user-images.githubusercontent.com/75047939/179815754-1ae0cc1b-a4c3-4a83-8bdf-9e4287eef85a.png)

**Comment by BillyG83** [comment]
hey @MateusbrMedeiros i keep telling people to stop using Select as it is not production ready, instead the devs should use Select with `traditionalHTML5 = true`
