### ISSUE TITLE
Cannot find module 'web3uikit' or its corresponding type declarations.

### ISSUE THREAD

**Issue by sanjaydefidev** [web3ui/web3uikit#739]
Hey, I just installed `web3uikit` on a fresh project and I am getting following error.

`Cannot find module 'web3uikit' or its corresponding type declarations.ts(2307)`

my code
```typescript
import { ConnectButton } from "web3uikit";
export default function Header() {
    return <div></div>;
}

```

Here what I am using
```javascript
"dependencies": {
    "moralis": "^1.9.1",
    "next": "12.2.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-moralis": "^1.4.0",
    "web3uikit": "^1.0.2"
  },
  ```

**Comment by AbhinavMV** [comment]
Hey @sanjaydefidev 
TY for using the kit ❤️ 

Could you change web3uikit version to `0.1.170` in your package.json 
We are working on monorepo and it has some publish issues right now we are trying to fix it. Will update soon

**Comment by sanjaydefidev** [comment]
Thanks @AbhinavMV 
I have used `0.1.170` and it's now fix. Hope to see fixes for the latest version.

**Comment by zahraha97** [comment]
Yeah it works for me also.

**Comment by adriadrop** [comment]
Also had
"web3uikit": "^1.0.3" and it was bust. Worked with suggested version

**Comment by AbhinavMV** [comment]
Hey @zahraha97 , @adriadrop 
TY for using the kit.

The web3uiKit monorepo is now live please import the slices of the repo you need as so

For all web3 components like connect wallet, Native Balance, etc.....
`yarn add @web3uikit/web3`

For all core components like button, input etc..
`yarn add @web3uikit/core`

For all icons
`yarn add @web3uikit/icons`
