### ISSUE TITLE
@web3uikit/core @web3uikit/web3 @web3uikit/icons not found

### ISSUE THREAD

**Issue by PatrickAlphaC** [web3ui/web3uikit#740]
```
yarn add --dev  @web3uikit/core @web3uikit/web3 @web3uikit/icons
yarn add v1.22.18
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@web3uikit%2fcore: Not found".
info If you think this is a bug, please open a bug report with the information provided in "XXX.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

You get a similar error with `npm`.

Also, if you look at the NPM website, you can't find these packages either.

https://www.npmjs.com/search?q=web3uikit

The docs currently show to use this api to install web3uikit. Can we please fix?

**Comment by locothedev** [comment]
Hey @PatrickAlphaC . We are currently experiencing some publishing issues with github actions we raised an issue here
https://github.community/t/error-changing-workflow-permissions/263648

Please install 0.1.170 for a stable legacy web3uikit version (non-monorepo-version)

**Comment by PatrickAlphaC** [comment]
Thank you @locothedev !

**Comment by BillyG83** [comment]
thank you too @locothedev 💚

**Comment by BillyG83** [comment]
hey @PatrickAlphaC can we close this one? I will be pamping like crazy on twitter where we chat when its ready for monorepo

**Comment by BillyG83** [comment]
hey @PatrickAlphaC we did it thanks to @AbhinavMV 

from Discord 
```
We were finally able to publish our monorepo 🚀 🤩 
Give it a try 
For all web3 components like connect wallet, Native Balance, ENSAvatar etc.....
yarn add @web3uikit/web3

For all core components like button,input etc..
yarn add @web3uikit/core

For all icons
yarn add @web3uikit/icons
```

**Comment by BillyG83** [comment]
closing this one now @PatrickAlphaC as we spoke on twitter, you legend, Ty for your support!

**Comment by PatrickAlphaC** [comment]
❤️
