### ISSUE TITLE
[Hero] Refactor and match designs

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#750]
Hero has some problems

- hero should take children components like typography and button and lay them out nicely
- hero should take an optional component for image
- Illustration needs updated with this sweet Wizard to be added
- if the image is added please use the layout seen below
- do not use position absolute, use flex and give the image a max width and max height
- it should scale as seen in this design perfectly no matter what content, children or image size is passed

<img width="675" alt="CleanShot 2022-08-01 at 14 24 42@2x" src="https://user-images.githubusercontent.com/13779759/182159592-061c49e8-02b9-4a38-be5f-f46e03cab797.png">

**Comment by BillyG83** [comment]
make it killer DX @AbhinavMV and idiot proof 😁

**Comment by locothedev** [comment]
Would be great if title is optional too

**Comment by BillyG83** [comment]
@locothedev i think it would be best of you passed it children and an optional image component, then you can use whatever text you like

**Comment by BillyG83** [comment]
@AbhinavMV maybe make the title optional for now and we can remove it over time so there is no big braking changes

**Comment by AbhinavMV** [comment]
This is closed by #762
