### ISSUE TITLE
[Icon] home icon missing

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#752]
- can you add the home icon please
- dude i ❤️ the icon gallery
- can you run through it and make sure we are not missing any from figma, TY sir

**Comment by BillyG83** [comment]
@AbhinavMV just FYI amigo! there was an update

![Screenshot 2022-08-03 at 15 35 14](https://user-images.githubusercontent.com/13779759/182621271-8283ab94-e9d8-4d9c-b04d-c075e79e6f8c.png)

**Comment by AbhinavMV** [comment]
rocket icon is added as well 🙌🏻  #758
