### ISSUE TITLE
[ConnectButton] Typo exporting the component as ConnectWallet instead of ConnectButton

### ISSUE THREAD

**Issue by iuliannov** [web3ui/web3uikit#753]
The component `ConnectButton` is exported with a different name `ConnectWallet` in [index.tsx](https://github.com/web3ui/web3uikit/blob/master/packages/web3/src/lib/ConnectButton/index.tsx) in the latest @web3uikit/web3 package version
![Screenshot 2022-08-02 at 16 45 15](https://user-images.githubusercontent.com/97514036/182389964-ddf745a4-6962-4240-acd8-0d8b9affda20.png)

**Comment by AbhinavMV** [comment]
Closed by #755

**Comment by AbhinavMV** [comment]
TY @iuliannov  🙌🏻
