### ISSUE TITLE
[Card] Icon text on top of tooltip text.

### ISSUE THREAD

**Issue by jvalentee** [web3ui/web3uikit#763]
![Screenshot_from_2022-08-07_00-55-34](https://user-images.githubusercontent.com/15859810/183309809-b6864f6d-2f19-4b27-8fda-d01cbe7c8af1.png)

The icon used for the tooltip in the Card element implements a description that hovers over the tooltip text.
The image above is taken directly from the [storybook](https://web3ui.github.io/web3uikit/?path=/story/4-ui-card--regular).

**Comment by AbhinavMV** [comment]
TY @jvalentee for using the kit and for the feedback 🙌🏻

**Comment by AbhinavMV** [comment]
Hey @jvalentee 
This issue should be fixed in the latest version `0.1.5`
Closed by #767
