### ISSUE TITLE
dispatch function from useNotification is not working correctly

### ISSUE THREAD

**Issue by sadityakumar9211** [web3ui/web3uikit#764]
I have used the useNotification() hook for notifications. The notification position is not working correctly in the deployed application. 
https://medichain.vercel.app/
The Github repository of this deployed site is: 
https://github.com/sadityakumar9211/medichain-nextjs

In the localhost, it is coming in the correct position in the bottom-right, but in the deployed file, it is coming on top of the header and shifting all the content down for the time it remains there.

**Comment by iuliannov** [comment]
has nothing to do with the uikit itself, you have to setup styled components to work with next js

**Comment by sadityakumar9211** [comment]
Hey @iuliannov I am not getting how using the styled component will help resolve my issue. Can you please explain a little more.

**Comment by iuliannov** [comment]
The components form web3uikit are built with styled-components, which doesnt work out of the box with nextjs. You have to setup nextjs to support styled-components so you can build your app successfully. Its easy to do, check [next.config.js](https://github.com/vercel/next.js/blob/canary/examples/with-styled-components/next.config.js) and [_document.tsx](https://github.com/vercel/next.js/blob/canary/examples/with-styled-components/pages/_document.tsx). These are the only thing you have to add to make it work

**Comment by AbhinavMV** [comment]
@sadityakumar9211 let us know if this fixes the issue.
TY for using the kit 😄 

TY @iuliannov for your help 🙌🏻

**Comment by AbhinavMV** [comment]
Hey @sadityakumar9211 
I am closing the issue since one of our community members was able to solve this same issue by the above solution by @iuliannov 🥳
Ping us on moralis web3uikit channel on discord if you are still facing this issue 🙌🏻
TY for using the kit 😄
