### ISSUE TITLE
[ConnectButton]: v2

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#792]

**Comment by BillyG83** [comment]
please drop any feature requests here

**Comment by BillyG83** [comment]
Hat says add:
```
- backgroundColor: string;
- textColor: string;
- bodyColor prop: string;
```

**Comment by abdul-kabugu** [comment]
here  is  what  I'm working  on 
 - custom text  (user  can  change  from  connect  button  to  something  else 
 - onSuccess event
 - balance     (the prop to  show / hide balance)
 -

**Comment by BillyG83** [comment]
@abdul-kabugu i am not sure this is going to work as an out of the box component anymore as we move away from moralis servers

**Comment by abdul-kabugu** [comment]
@BillyG83     TY  for  info ,  is  still  issue  open  ?  I  can  work  on it  ?

**Comment by BillyG83** [comment]
@abdul-kabugu sure you are welcome to work on it. the aim was to provide connect button without Moralis server and add some nice new features like customisation. I do not think it s possible without firebase or NextJS as a backend. But you could try or even just change the scope of this. FYI <Button/> now has customisation so you could use it in <ConnectButton/> and job done for V1

**Comment by BillyG83** [comment]
i'm going to close this as we have a new plan of how to re-create the functionality of Connect Button with NextJS or Firebase
