### ISSUE TITLE
Wrong logo for Cryptologo Coinbase

### ISSUE THREAD

**Issue by 3scava1i3r** [web3ui/web3uikit#794]
### Adding screenshot for reference
![Screenshot from 2022-09-04 14-34-04](https://user-images.githubusercontent.com/52003051/188306099-9ab12018-05c5-4102-a9a9-0b3f9d79c58c.png)

Correct logo

![image](https://user-images.githubusercontent.com/52003051/188306080-176df7f2-bcce-4726-8d7b-e737d112f9df.png)

**Comment by AbhinavMV** [comment]
Hey @3scava1i3r 
I have assigned this to you. let me know if you are not working this.. 🙌🏻

**Comment by 3scava1i3r** [comment]
I'll finish this soon
