### ISSUE TITLE
Support for more logos

### ISSUE THREAD

**Issue by 3scava1i3r** [web3ui/web3uikit#795]
Opening an issue to add logos like -

- Optimism
- Celo
- EOS

and many more

**Comment by AbhinavMV** [comment]
Hey @3scava1i3r 
I have assigned this to you. let me know if you are not working on this.. 🙌🏻

**Comment by 3scava1i3r** [comment]
@AbhinavMV I'll finish this asap

**Comment by heysagnik** [comment]
Can I take the task ?

**Comment by BillyG83** [comment]
i think i will close this issue for now and if anyone wants a logo they can add it with a PR
