### ISSUE TITLE
I installed @web3uikit/web in next-app  But localhost reported this error:

### ISSUE THREAD

**Issue by wangyangv1** [web3ui/web3uikit#800]
![image](https://user-images.githubusercontent.com/49341812/189012991-1131547a-f10b-4b27-bbe3-9cb414e0e2c9.png)
 
I just installed web3uikit/web without writing any code, this is my react package.json
<img width="447" alt="image" src="https://user-images.githubusercontent.com/49341812/189013105-c9930d07-b497-4f45-84b4-d9d2fbf121eb.png">

**Comment by wangyangv1** [comment]
<img width="257" alt="image" src="https://user-images.githubusercontent.com/49341812/189045480-8221566d-b59d-4aca-b1c8-f9bd1871bb72.png">
I wrote simple connect wallet button, I want to add nice ui to the button, but after I installed web3uikit I have a problem

**Comment by AbhinavMV** [comment]
Hey @wangyangv1 
TY for using the kit.
Could you install the following packages and try again.
```
"moralis-v1": "^1.11.0",
"react-moralis": "^1.4.2",
"@web3uikit/web3": "^0.1.9",
```

**Comment by wangyangv1** [comment]
> Hey @wangyangv1 TY for using the kit. Could you install the following packages and try again.
> 
> ```
> "moralis-v1": "^1.11.0",
> "react-moralis": "^1.4.2",
> "@web3uikit/web3": "^0.1.9",
> ```

Thank you so much, this is so helpful to me
