### ISSUE TITLE
[web3] rename Moralis v1 web3

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#812]
rebrand section 1 web3 components in storybook to `web3 - Parse`

this will also require any links in the readme files to be updated

**Quick mockup:**
![Screenshot 2022-09-29 at 09 00 04](https://user-images.githubusercontent.com/13779759/192961830-18a13b18-bdbe-4780-b0f9-cd95b8b3e7eb.png)

**Comment by nikita12c** [comment]
Here , should we need to rename the 'WEB3V2' -----> 'WEB3 - PARSE'
and update the related links to this section.....
If I guess this correct, I am happy to try solving this issue ?

**Comment by AbhinavMV** [comment]
TY will assign you this issue. 🙌🏻 

While you are at it could you also add this to the readme:
Where to add: (position marked in white)
![image](https://user-images.githubusercontent.com/35369843/196093036-61672785-8c2d-4a51-ab3e-e911f7192f94.png)


what to add-> ‼️ Moralis servers will be deprecated soon. To continue using this package, self host your server by following the steps from [moralis docs](https://docs.moralis.io/docs/v1-server-self-hosting#next-steps)

**Comment by nikita12c** [comment]
Thanks for assigning Abhinav. I did these changes : https://github.com/web3ui/web3uikit/pull/838
Please checkout my pull request.

**Comment by AbhinavMV** [comment]
Closed as completed by #838
