### ISSUE TITLE
[Form]: Adding upload component to the form component

### ISSUE THREAD

**Issue by Bulalu** [web3ui/web3uikit#830]
I feel like the form component should have the upload feature so that we can be able to upload files directly within the form

**Comment by AbhinavMV** [comment]
TY @Bulalu for using the kit and feedback ❤️ 

Things to do in the issue:
1. Integrate upload component in the core package to be used with form component.
2. On form submit upload component data must be present return in form component's `onSubmit` func
3. Make any changes to upload component to be able to do this without breaking current functionality (if needed)
