### ISSUE TITLE
[Table]: New story with Custom Loading component

### ISSUE THREAD

**Issue by nikita12c** [web3ui/web3uikit#834]
In Table component inside Layout section  , Loading table UI is not proper I guess. 
It looks likes this below image initially :

![initial-tableLoader](https://user-images.githubusercontent.com/66167434/195669039-679bb6d6-75b0-48f8-a71a-6a3b6c4a5ee8.png)

After I merged 3 Skeleton rows inside table with proper Layout , I changed the Loading Table UI , now looks like this below img  : 

![afterAddingSkeleton](https://user-images.githubusercontent.com/66167434/195669246-0d7beab5-193b-4edf-ada2-33431b9f430f.png)

I changed just one file by adding this feature in it.
I think this looks pretty ! Should I do a pull request of my code.

**Comment by AbhinavMV** [comment]
Hey @nikita12c 
Feel free to create a PR for review. 🎉

**Comment by nikita12c** [comment]
Yeah! Done @AbhinavMV  !

**Comment by AbhinavMV** [comment]
Great work, TY for your contribution 🥳 

closed as completed by #835
