### ISSUE TITLE
Issue in DatePicker Static Date when changed type from date to month

### ISSUE THREAD

**Issue by nikita12c** [web3ui/web3uikit#836]
In Datepicker component inside Forms section, 
When type is initially set to 'date' and static value is set then it works fine .  Ref below img :
![initialDateStatic](https://user-images.githubusercontent.com/66167434/196046949-413290b4-343f-433a-a860-27fa8ebbe012.png)

But when the type is set to month, it doesn't works instead shows blank line. This is because default value is set as 'yyyy-mm-dd' which is not acceptable for type=month. For month type it must be 'yyyy-mm'.
![afterMonth](https://user-images.githubusercontent.com/66167434/196047089-c72e65f3-e88f-479a-a2cd-6fb0b3d715a7.png)
 
So I think a new story must be created here for the case of type-month with 'yyyy-mm' as a static value to let the users know that both static date format is different for type month.

Should I create a PR for this ?

**Comment by AbhinavMV** [comment]
TY 🥳 
Closed as completed by #837
