### ISSUE TITLE
Refactor: Cryto Cards, Crypto Logo & Illustration 

### ISSUE THREAD

**Issue by AbhinavMV** [web3ui/web3uikit#854]
Issue -> to add a single network logo you have to update 3 components. Illustration -> crypto Logo -> crypto cards

Required -> Make a single source of truth as an Illustration and adding logo to illustration would automatically add it to other components

EDIT: also make the component tree shakable, take reference from button component to use lazy imports... fallback component could be loading

**Comment by BillyG83** [comment]
nice @AbhinavMV are the Illustrations tree shakable?

**Comment by AbhinavMV** [comment]
not right now, but nice idea we can use lazy import like the button to make it tree shakable fallback component can be loading component... will edit the issue description 🙌

**Comment by AbhinavMV** [comment]
Closed as completed by #876
