### ISSUE TITLE
[Upload] support for other file types

### ISSUE THREAD

**Issue by 0xTijan** [web3ui/web3uikit#862]
Right now the Upload component only supports images. If user uploads pdf or any other type the component breaks:

![image](https://user-images.githubusercontent.com/88556617/198068137-d09a94ab-21c4-497e-af3b-6095660916ae.png)
(I uploaded pdf)

I was thinking maybe we could fix this and add another prop for devs to be able to specify witch file types are accepted.

**Comment by BillyG83** [comment]
it would be cool to show what is supported for upload, the dev would maybe want to specify this as a prop object

```
supportUploads = {
  image: true,
  pdf: false,
   ... any else?
```

also make sure to not allow anything to be uploaded this could cause a vulnerability

**Comment by 0xTijan** [comment]
One option is to create a object like you suggested of [discrete types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#types) and than create the needed string for the input attribute ``${keyValue}/*`` :
```
	supportedUploads: {
		application: boolean,
		audio: boolean,
		example: boolean,
		font: boolean,
		image: boolean,
		model: boolean,
		text: boolean,
		video: boolean
	}
```
but this would remove the freedom from devs to be able to specify exactly which files to accept (for example only .png and not .jpeg)

Since there are many of these types I propose that devs specify exactly what they want (which makes it the safest and the most customizable way I think) - [see here](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept#limiting_accepted_file_types). Thats why I implemented it in that way in my PR. 🙌
