### ISSUE TITLE
Can your team please create a web3 connectButton which is compatible with Moralis Auth?

### ISSUE THREAD

**Issue by tomwhiteman** [web3ui/web3uikit#871]
Hey guys, 

The current connect button does not work with Moralis Auth on a self-hosted server. The only option is to manually change the code and build the library. As per this post on the Moralis forum, there is a demand for this feature as well. Please consider making this change/update. 
https://forum.moralis.io/t/solved-how-to-use-moralis-auth-on-self-hosted-server-with-web3uikit-connect-button/20522
Thank you!

**Comment by BillyG83** [comment]
@tomwhiteman hey thanks for the suggestion, i am working on this using Next JS. Sorry its mostly on Saturdays but i am making progress

**Comment by BillyG83** [comment]
would a NextJS solution work for you?

**Comment by whoopydev** [comment]
Hey, yes of course! I'm using Nextjs for my production. Thanks!

**Comment by keenleads** [comment]
I am also interested in this. Thank you for fixing. Do we have an ETA on when we can expect the ConnectButton to work with Moralis Self Hosted servers?

**Comment by BillyG83** [comment]
@whoopydev and @keenleads sorry for the late reply, its been very busy in the last weeks and i managed to move house too 😅 

Have you seen the [Next-JS / Morlais boilterplate](https://github.com/ethereum-boilerplate/ethereum-boilerplate)?

it has Morlais Auth Built into it
