### ISSUE TITLE
Add lens profile login

### ISSUE THREAD

**Issue by PatrickAlphaC** [web3ui/web3uikit#903]
To the `ConnectButton` it would be great to have a flag to connect to lens protocol to return an auth token. 

https://docs.lens.xyz/docs/authentication-quickstart

**Comment by BillyG83** [comment]
hey @PatrickAlphaC thanks for checking in with us again. The Connect Button was powered by an old Moralis service that we no longer support. I am thinking hard about the next steps for the kit but have become delayed by a new project we are building. I will be back to the web3 components kit in Q1 2023 to make a road map of how we move forwards but I just wanted to say, thanks for the feedback and support 💚

**Comment by PatrickAlphaC** [comment]
Love this tool :), have a great holiday break!

**Comment by BillyG83** [comment]
sorry @PatrickAlphaC 

I am closing this issue as soon this section of the repo will be depreciated so no further developed should be expected. Thanks

If you have questions please reach out to me on Moralis Discord

Thanks a lot for supporting the kit, i hope the next iteration of our web3 slice of the repo is equally exciting for you. I hope it will make building dapps even easier
