### ISSUE TITLE
feature - Allow WalletModal wallets to be configurable as props

### ISSUE THREAD

**Issue by jhhb** [web3ui/web3uikit#906]
Hello, here's a feature request I had and would be happy to work on with some input from the team. Thanks for any help that can be provided.

### Context
- In [WalletModdal/config.ts](https://github.com/web3ui/web3uikit/blob/7ad6b929ff6144efdf495951113adfd7443e84e6/packages/web3/src/lib/WalletModal/config.ts#L14), there is a hard-coded array of elements that are used for rendering all of the Wallet-specific UI elements in the modal.
- While I was working on an application, I wanted to be able to explicitly configure which providers were "valid" for my application; basically, I didn't want to give a user of my application the impression that Safepal was supported to the same degree that, e.g., Metamask is. 

### Proposal

- Continue to use the hard-coded array by default, but allow the user to pass in a `connectors` prop, which overrides the hardcoded list; the `connectors` prop would be an array of the same type as the existing `connectors` variable

While this solves my issue, it creates a UX problem, which is that if a user passes in an odd number of wallet configurations, then they will get a wallet that has one "empty" grid cell. If that's enough of a problem for a consumer, there are ways to fix it, but I'd probably need some design input on how to handle that case.

For example, one way to solve it would be to make the odd element span the entire width of the container, but I think this would require changing [GridStyled](https://github.com/web3ui/web3uikit/blob/7ad6b929ff6144efdf495951113adfd7443e84e6/packages/web3/src/lib/WalletModal/WalletModal.styles.ts#L45) to be `display:flex` instead of `display:grid`, and would also require changes to its children.

### Questions
1. Does allowing wallets to be configurable by a consumer make sense?
2. If so, how do you suggest handling the case of an odd number of wallet configs? Do nothing? My suggestion above? Something else?

**Comment by jhhb** [comment]
here is an example of the UI I mention above that would happen by default with an odd number of elements:

![Screen Shot 2022-11-19 at 3 06 14 PM](https://user-images.githubusercontent.com/12632889/202871605-390bda90-9281-4375-ae17-67e7b36caba8.png)

And here is an example of what the UI could look like with some changes to the styling:

![Screen Shot 2022-11-19 at 3 08 03 PM](https://user-images.githubusercontent.com/12632889/202871646-86fdf3bc-e84e-469d-bbd9-0207f8b15ad4.png)

**Comment by BillyG83** [comment]
Hi @jhhb thanks for taking an interest in the kit. 

Sure, I think this sounds like a nice feature and we always welcome open source contributions to the kit. In and for the flex vs grid question I think the desired UI is achievable with both but whatever solution you prefer is fine with me.

Ping me when you complete the pull request and i'll glad review it for you =]

**Comment by BillyG83** [comment]
I am closing this issue as soon this section of the repo will be depreciated
