### ISSUE TITLE
[Icon] New icons needed

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#909]
i need some new icons added to the kit please

see `packages/icons`

New icons will need exported like the other, just find one like `AddUser` and copy =]

Airdrop
![air-drop](https://user-images.githubusercontent.com/13779759/203023258-c61c1f85-f938-4efd-adb3-1da9826023d0.svg)

NFT Cat
![nft-cat](https://user-images.githubusercontent.com/13779759/203023260-9a2d43db-a0bf-4bca-8cba-68caef83924a.svg)

Token
![token](https://user-images.githubusercontent.com/13779759/203023262-0fb06f7b-47ca-426b-9bee-d11056ae4aac.svg)

Wallet
![wallet](https://user-images.githubusercontent.com/13779759/203023266-8c684dc5-8199-40dc-bc2f-42ed1f7607ce.svg)

Beans
![beans](https://user-images.githubusercontent.com/13779759/203023270-b04975a1-a5c3-43da-ae80-b5e58d4a16fb.svg)

Bean
![bean](https://user-images.githubusercontent.com/13779759/203026472-50214d49-0ac9-4e4f-9e16-e485930b6f17.svg)

**Comment by AbhinavMV** [comment]
@0xTijan 
maybe you already noticed but just an FYI Some of these icons are already present maybe with a different name
Make sure to check existing icons before adding new ones 😄 🙌🏻

**Comment by AbhinavMV** [comment]
![Dai](https://user-images.githubusercontent.com/35369843/203032704-31848d85-d453-4271-97a4-dc4ddf4f2190.svg)

Could you please add this one too @0xTijan ?
