### ISSUE TITLE
[ICON]: bug NFTCat not exported

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#918]
maybe just a type or maybe forgotten in the export, no biggy but could you look into this one for me please @0xTijan `Token` works so just do that same as you did with it, please and TY

![Screenshot 2022-11-24 at 16 37 52](https://user-images.githubusercontent.com/13779759/203822286-ec9f13cd-1d19-42bf-8fb1-959250fcf51a.png)

**Comment by 0xTijan** [comment]
Tried it out in new react app and works fine for me, maybe you have an older version of web3uikit installed?

![image](https://user-images.githubusercontent.com/88556617/203827790-fa73b2ff-caae-4fb7-9c46-ef133bf81a12.png)

**Comment by BillyG83** [comment]
@0xTijan I think it didnt work in live storybook because it was missing the changeset file... then locally for me because i forgot to `pnpm build`

thanks for the feedback i will close this now and merge your other icon MR... TY DUDE!!!!
