### ISSUE TITLE
Impossible to fetch nfts with the NFTBalance function

### ISSUE THREAD

**Issue by jbastruz** [web3ui/web3uikit#939]
Hi, 

I'm trying to develop a dapp to show the list of nfts owned by the connected wallet. On this purpose, I tried to use NFTBalance function in this library, but unfortunately nothing happened no error in my console, but nothing on my dapp either... 

Here is my simplified code :

```
import { NFTBalance } from "web3uikit"

export default function GraphExample() {

    return (
        <div>
            hi
            <NFTBalance address="0x951Eb8643E48A3B6d6d6AA7706B643AEE9B42f52" chain="eth" />
        </div>
    )
}
```

the expected result should be that: 
![image](https://user-images.githubusercontent.com/22955529/206482333-dfdf2053-50e7-4cc8-aaf4-af43a0b47f44.png)
like it seems to work [here](https://web3ui.github.io/web3uikit/?path=/docs/1-web3-parse-nft-balance--default)

I didn't find any solution on internet...
I'm pretty sure that I missed something obvious, but I can't see what.
Could someone help me ? 
thanks !

**Comment by AbhinavMV** [comment]
Hey @jbastruz ,
you can read this to setup react-moralis in your project
https://github.com/web3ui/web3uikit/blob/master/packages/web3/README.md#nftbalance-

Unfortunately, If you are new to moralis this won't work without self-hosting a server. You can read more about self-hosting here - https://docs.moralis.io/docs/self-hosted-moralis-server
 
Recommended:
You can use moralis API (recommended) and create your UI 😄 
Here are the docs to use the API - https://docs.moralis.io/docs/how-to-get-all-nfts-owned-by-an-address

**Comment by jbastruz** [comment]
ok thanks, i'll try to find an other solution for my dapp in this case, thanks for your help 😊
