### ISSUE TITLE
[Modal]: add z-index prop to modal

### ISSUE THREAD

**Issue by AbhinavMV** [web3ui/web3uikit#964]

**Comment by SebastianLF** [comment]
Interested to work on this one. Can you give more context, please?

**Comment by AbhinavMV** [comment]
Hey @SebastianLF, Great to hear that you are interested to work on this 🤩 

Context: 
The modal component has hardcoded z-index right now. I was thinking of adding a new prop to the component called -> `zIndex` . And based on this value the modal will get a z-index. Also whatever value is used right now should be the default value. so that there are no breaking changes 😄 

I will assign you this issue. Let me know if you want any help, btw you can join moralis discord channel and ask for any help in web3uikit channel 🙌🏻

**Comment by SebastianLF** [comment]
Thanks for this clear explanation. Let's try it!

**Comment by AbhinavMV** [comment]
Hey @SebastianLF 👋🏻 
How is this task going? 
Let me know if you are facing any issues 🙌🏻

**Comment by SebastianLF** [comment]
Sorry, will work today on it :)

**Comment by AbhinavMV** [comment]
Nice work @SebastianLF 🥳 

Closed as completed by #981
