### ISSUE TITLE
Icon - MessageCircle color prop

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#966]
MessageCircle is black no matter what `color` i pass to it

**Comment by AbhinavMV** [comment]
@BillyG83 
MessageCircle seems to be working as expected, i have identified some other icons with this problem (most likely a problem with svg).

![image](https://user-images.githubusercontent.com/35369843/209637281-cdf14914-e65e-4a61-a2af-623176075435.png)

**Comment by BillyG83** [comment]
@AbhinavMV you are correct it is `MessageSquare`
![Screenshot 2022-12-29 at 13 07 17](https://user-images.githubusercontent.com/13779759/209949156-5e4d90ac-60ee-4b8e-bc33-8358ce2d4ee5.png)

I will also fix `CheckCircle`
![Screenshot 2022-12-29 at 13 07 24](https://user-images.githubusercontent.com/13779759/209949165-e5445f6c-5f4b-4179-aaf9-1aa45946a74d.png)


and finally i had no idea the color there was there, thats amazing DX dude!
![Screenshot 2022-12-29 at 13 08 35](https://user-images.githubusercontent.com/13779759/209949183-1ac268fb-6a08-4d8a-b936-5db880a2568a.png)

look at my hacked preview, poor input lol
