### ISSUE TITLE
Icon: all icons fixed width

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#967]
if an Icon is flexed with another element and the page or its container gets too tight, it gets very tiny, this should not happen

## problem
![Screenshot 2022-12-26 at 14 30 50](https://user-images.githubusercontent.com/13779759/209554170-ab80e891-6cac-4e71-99ec-e650e4cbed88.png)

## fix
add a div around the Icon and use
```
width: props.width
min-width: props.width
height: props.height
min-height: props.height
```
![Screenshot 2022-12-26 at 14 31 00](https://user-images.githubusercontent.com/13779759/209554274-22b03ca1-bc80-4afd-a55e-76f4c6ae67e4.png)

please make this the default behaviour of Icon so it never shrinks in small spaces. Maybe it would be nice to offer an `isResponsive` props for people who like the bug as a feature

**Comment by AbhinavMV** [comment]
closed as completed by #974
