### ISSUE TITLE
BannerStrip: new features

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#968]
- import `TCustomize` prop and set up all the types that can be used: see InputNew or Credentials for an example of this
- Implement `slots` feature: see InputNew

**Comment by SebastianLF** [comment]
Can I ?

**Comment by SebastianLF** [comment]
We agree that adding the `TCustomize` feature incurs some breaking changes ?

**Comment by AbhinavMV** [comment]
@SebastianLF I don't think there will be any breaking changes, there will be a new prop that can be used to add elements at the beginning and end of the component.

Could you explain how there would be a breaking change? Maybe we can find a way to avoid it. 😄 (if you have already completed, you could also create a PR if you want to show the change)

**Comment by SebastianLF** [comment]
Prop `borderRadius = '0px',` on component `BannerStrip` will be redudant with `customize` property. Am I wrong ?

**Comment by SebastianLF** [comment]
Got it!
