### ISSUE TITLE
`Card` typing issue

### ISSUE THREAD

**Issue by YosephKS** [web3ui/web3uikit#97]
### Description

Looks like some typing issue here that does not allow `Card` to have multiple children. I copied the code from [Storybook](https://web3ui.github.io/web3uikit/?path=/docs/ui-card--regular-selected):
```ts
<Card
   description="Create your own cryptocurrency / token"
   title="ERC20-Token"
   tooltipText="Create your own ERC20 Token"
>
   <Illustration height="180px" logo="token" width="100%" />
</Card>
```

but if I add more than 1 children, then it'll work fine.

### Image

![Screenshot from 2022-01-25 20-50-12](https://user-images.githubusercontent.com/48710170/150989660-64fc7a16-795f-45f8-8f5f-01323a493637.png)

**Comment by YosephKS** [comment]
can be hacked by this btw 😄 
```tsx
<Card
   description="Create your own cryptocurrency / token"
   title="ERC20-Token"
   tooltipText="Create your own ERC20 Token"
>
   <Illustration height="180px" logo="token" width="100%" />
   <div />
</Card>
```

**Comment by locothedev** [comment]
Fixed. TY @YosephKS 👍

**Comment by YosephKS** [comment]
> Fixed. TY @YosephKS +1

Niceee! thanks @locothedev 🔥 will check it out 🙌🏼
