### ISSUE TITLE
IPFSInput doesn't work properly

### ISSUE THREAD

**Issue by jbastruz** [web3ui/web3uikit#987]
Hi guys,

I try to implement the possibility to import image from my computer to IPFS thanks to IPFSInput and NFT.storage.

my code for now looks like this 

```  
import { IPFSInput } from "web3uikit"    

...
   
<div className="App">
           <div className="container">
                {error && <p>{error}</p>}
                <h1>Mint an {data.name} NFT !</h1>
                <p className="cost">Each NFT costs {0.0} AVAX (excluding gas fees)</p>
                <button onClick={mint}>BUY {data.description} NFT</button>
            </div>
            <div>
                <IPFSInput onFinish={function noRefCheck() {}} saveToIPFS theme="withIcon" />
            </div>
        </div>
```

this code is an extract of my global code, my point is the IPFSInput make the code crash, saying 

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

impossible to find a solution,
did someone has the same issue ? how to fix it ?

thanks for your help 😊

**Comment by AbhinavMV** [comment]
Hello 👋🏻 

What version of web3uikit are you using?

Could you try using it as follows.
```
import {IPFSInput} from '@web3uikit/web3';
.....
<IPFSInput onFinish={(e)=>{console.log(e)}} saveToIPFS theme="withIcon"/>
.....
```

FYI This component does require servers which is deprecated now. you can try self-hosting server - https://docs.moralis.io/web3-data-api/self-hosted-moralis-server/self-hosted-moralis-server#self-hosting-a-parse-server
or create your own component using moralis API (recommended) - https://docs.moralis.io/web3-data-api/evm/ipfs-api#what-is-the-ipfs-api

**Comment by jbastruz** [comment]
ok, thats probably why I can't use it, I have a new error saying : 

```
error - ./node_modules/@web3uikit/web3/node_modules/react-moralis/lib/index.esm.js:3:0
Module not found: Can't resolve 'moralis-v1'
```

does someone knows an alternatives to be able to upload image through an UI button to upload it on IPFS without any moralis server ?

**Comment by AbhinavMV** [comment]
Looks like you are following an old tutorial, to use self-hosted servers you have to install `moralis-v1` instead of `moralis`

Without servers, you have to  create your own component using moralis API - https://docs.moralis.io/web3-data-api/evm/ipfs-api#what-is-the-ipfs-api
This would also require some sort of backend.

Could you create a post on moralis discord server -> `moralis-sdk-help` channel, our awesome engineers will help you out 😄 

I will close this issue since this repo is for web3uikit issues only, hope you understand 😄
