### ISSUE TITLE
[Illustration]: add optional fill prop

### ISSUE THREAD

**Issue by AbhinavMV** [web3ui/web3uikit#996]
- Add optional `fill` prop. Also add comment on top of this `Will only work for web3 chain illustrations` 
- this will help give color to illustration (mostly for chain illustrations rest of them have hardcoded colors)
- make the default fill color = white
- update chain svgs code. In svg tag update `fill = "currentColor"` and in remove `fill="white"` from other tags

**Comment by niteshseram** [comment]
Hi @AbhinavMV Can I work on this?

**Comment by AbhinavMV** [comment]
Hey @niteshseram 

sure, will assign the issue to you. Looking forward to your PR.

Let us know if you need any help, you can reach out to us on moralis discord server 🙌
