### ISSUE TITLE
[Switch] optional label on the left

### ISSUE THREAD

**Issue by dani69654** [web3ui/web3uikit#998]
Would be nice to have an optional label on the left to switch between two options. <br />

In the example below, the user should be able to switch between API and Streams and the switch color should remain green.

![Screenshot 2023-01-06 at 16 54 07](https://user-images.githubusercontent.com/60792849/211048366-9c268cea-1381-4294-93e5-0cf485f9ea18.jpg)

**Comment by tarunyadav1** [comment]
I want to take this issue. Can you please assign it?

**Comment by BillyG83** [comment]
ok dont need today but soon, let me know if i can take over @tarunyadav1 or if you have something close its all yours buddy, TY

**Comment by BillyG83** [comment]
@tarunyadav1 you can ask me anything. Discord is best for fast response `@billgil`

**Comment by BillyG83** [comment]
ok imma take this one over as @KristamMoffett already made the perfect fit in Money project and i can use his code. easy 🤩
